/* ============================================================================
 * Reconstructed source: :five.c
 * Generated by armfd --reconstruct-sources from launchme.sym
 * ============================================================================ */

// five.c - scene/decision driver.
#include "pdwt_scenes.h"

#include "3do_types.h"
#include "pdwt_app.h"
#include "pdwt_decision_audio.h"
#include "pdwt_input.h"
#include "pdwt_os.h"
#include "pdwt_scene_control.h"
#include "pdwt_timing.h"

#include "celutils.h"
#include "event.h"
#include "filefunctions.h"
#include "item.h"
#include "kernel.h"
#include "task.h"

#include "stdio.h"
#include "stdlib.h"
#include "string.h"

#define PIC(name, time) {name, 0, time}
#define DEC(name, x, y, w, h) {name, 0, x, y, w, h}

int32 point;
int32 startover;

static DecData dec13[3] =
{
  DEC("dec13a.aiff", 30, 20, 80, 60), DEC("dec13b.aiff", 120, 60, 80, 60),
  DEC("dec13c.aiff", 210, 100, 80, 60)
};

static DecData dec16[2] = {DEC("dec16a.aiff", 52, 20, 76, 90),
                           DEC("dec16b.aiff", 170, 60, 120, 90)};

static DecData dec18[2] = {DEC("dec18a.aiff", 52, 20, 76, 90),
                           DEC("dec18b.aiff", 170, 60, 120, 90)};

static DecData dec20[2] = {DEC("dec20a.aiff", 60, 20, 60, 90),
                           DEC("dec20b.aiff", 170, 60, 120, 90)};

static DecData dec22[2] = {DEC("dec22a.aiff", 52, 20, 76, 90),
                           DEC("dec22b.aiff", 170, 60, 120, 90)};

static DecData dec23[2] = {DEC("dec23a.aiff", 30, 20, 120, 90),
                           DEC("dec23b.aiff", 170, 60, 120, 90)};

static DecData dec25[2] = {DEC("dec25a.aiff", 60, 20, 60, 90),
                           DEC("dec25b.aiff", 170, 60, 120, 90)};

static DecData dec26[2] = {DEC("dec26a.aiff", 52, 20, 76, 90),
                           DEC("dec26b.aiff", 170, 60, 120, 90)};

static DecData dec28[2] = {DEC("dec28a.aiff", 52, 20, 76, 90),
                           DEC("dec28b.aiff", 170, 60, 120, 90)};

static DecData dec29[2] = {DEC("dec29a.aiff", 30, 20, 120, 90),
                           DEC("dec29b.aiff", 170, 60, 120, 90)};

static DecData dec30[3] =
{
  DEC("dec30a.aiff", 50, 20, 40, 60), DEC("dec30b.aiff", 126, 60, 68, 60),
  DEC("dec30c.aiff", 210, 100, 80, 60)
};

static DecData dec31[2] = {DEC("dec31a.aiff", 52, 20, 76, 90),
                           DEC("dec31b.aiff", 170, 60, 120, 90)};

#define BULLETHOLE_CEL_PATH "$boot/tuntest/sc25/bullethole.cel"
#define BULLETHOLE_BG_FLAGS 0x37644000UL
#define BULLETHOLE_PIXC 0x1F811F00UL
#define BULLETHOLE_SCREEN_W 320
#define BULLETHOLE_SCREEN_H 240
#define BULLETHOLE_TEMP_SIZE 0x25800
#define BULLETHOLE_TEMP_MEMTYPE (MEMTYPE_STARTPAGE | MEMTYPE_VRAM)
#define BULLETHOLE_BITMAP_NODE 0x203
#define BULLETHOLE_BMTAG_WIDTH 11
#define BULLETHOLE_BMTAG_HEIGHT 12
#define BULLETHOLE_BMTAG_BUFFER 13
#define BULLETHOLE_RANDOM_X_SCALE 640UL
#define BULLETHOLE_RANDOM_Y_SCALE 480UL
#define BACKPIC_MEMTYPE (MEMTYPE_STARTPAGE | MEMTYPE_VRAM | MEMTYPE_CEL)
#define RAW_PAD_SELECT 0x08000000UL
#define RAW_PAD_UP 0x10000000UL
#define RAW_PAD_DOWN 0x20000000UL
#define RAW_PAD_LEFT 0x40000000UL
#define RAW_PAD_RIGHT 0x80000000UL
#define RAW_PAD_STEPBACK 0x00400000UL
#define SHOWCASE_MAX_TRANSITIONS 256
#define RAW_PAD_HELP 0x00200000UL
#define HILITE_PIXC 0x9B419B41UL
#define HILITE_SELECTED_PIXC 0x96009600UL
#define DECISION_SPEECH_PATH_FORMAT "$boot/tuntest/dec/%s"
#define DECISION_SPEECH_BUFFER_SIZE 0x8000
#define DECISION_SPEECH_AMPLITUDE 0x4000
#define STORY_AUDIO_BUFFER_COUNT 4
#define STORY_AUDIO_BUFFER_SIZE 0x10000
#define STORY_AUDIO_AMPLITUDE 0x7fff

static PicData dsc15[17] =
{
  PIC("sc1501cel", 315),
  PIC("sc1502cel", 641),
  PIC("sc1503cel", 86),
  PIC("sc1504cel", 641),
  PIC("sc1505cel", 131),
  PIC("sc1506cel", 551),
  PIC("sc1507cel", 221),
  PIC("sc1508cel", 1481),
  PIC("sc1509cel", 281),
  PIC("sc1510cel", 551),
  PIC("sc1511cel", 30),
  PIC("sc1512cel", 945),
  PIC("sc1513cel", 375),
  PIC("sc1514cel", 461),
  PIC("sc1515cel", 281),
  PIC("sc1516cel", 566),
  PIC("sc1517cel", 116)
};

static PicData dsc16[9] =
{
  PIC("sc1601cel", 435),
  PIC("sc1602cel", 609),
  PIC("sc1603cel", 549),
  PIC("sc1609cel", 504),
  PIC("sc1604cel", 39),
  PIC("sc1605cel", 459),
  PIC("sc1606cel", 2079),
  PIC("sc1607cel", 459),
  PIC("sc1608cel", 805)
};

static PicData dsc17[14] =
{
  PIC("sc1701cel", 210),
  PIC("sc1702cel", 398),
  PIC("sc1703cel", 609),
  PIC("sc1704cel", 488),
  PIC("sc1705cel", 579),
  PIC("sc1706cel", 548),
  PIC("sc1707cel", 579),
  PIC("sc1708cel", 578),
  PIC("sc1709cel", 429),
  PIC("sc1710cel", 398),
  PIC("sc1711cel", 489),
  PIC("sc1712cel", 278),
  PIC("sc1713cel", 279),
  PIC("sc1714cel", 278)
};

static PicData dsc18[20] = {PIC("sc1801cel", 270), PIC("sc1802cel", 252), PIC("sc1803cel", 252),
                            PIC("sc1804cel", 252),
                            PIC("sc1805cel", 252), PIC("sc1806cel", 252), PIC("sc1807cel", 252),
                            PIC("sc1808cel", 237),
                            PIC("sc1809cel", 252), PIC("sc1814cel", 72),  PIC("sc1810cel", 372),
                            PIC("sc1811cel", 282),
                            PIC("sc1812cel", 357), PIC("sc1813cel", 642), PIC("sc1814cel", 942),
                            PIC("sc1815cel", 702),
                            PIC("sc1816cel", 642), PIC("sc1817cel", 582), PIC("sc1819cel", 582),
                            PIC("sc1818cel", 465)};

static PicData dsc20[12] =
{
  PIC("sc2001cel", 420),
  PIC("sc2002cel", 430),
  PIC("sc2003cel", 1283),
  PIC("sc2004cel", 280),
  PIC("sc2005cel", 190),
  PIC("sc2006cel", 400),
  PIC("sc2007cel", 310),
  PIC("sc2008cel", 173),
  PIC("sc2009cel", 160),
  PIC("sc2010cel", 160),
  PIC("sc2011cel", 430),
  PIC("sc2012cel", 420)
};

static PicData dsc21[22] = {PIC("sc2101cel", 165), PIC("sc2102cel", 344), PIC("sc2103cel", 164),
                            PIC("sc2104cel", 269),
                            PIC("sc2105cel", 59),  PIC("sc2106cel", 539), PIC("sc2107cel", 284),
                            PIC("sc2108cel", 224),
                            PIC("sc2109cel", 44),  PIC("sc2110cel", 434), PIC("sc2111cel", 224),
                            PIC("sc2112cel", 494),
                            PIC("sc2113cel", 74),  PIC("sc2114cel", 104), PIC("sc2115cel", 104),
                            PIC("sc2116cel", 104),
                            PIC("sc2117cel", 104), PIC("sc2118cel", 104), PIC("sc2119cel", 104),
                            PIC("sc2120cel", 104),
                            PIC("sc2121cel", 89),  PIC("sc2122cel", 74)};

static PicData ssc22[33] =
{
  PIC("sc2201cel", 300), PIC("sc2202cel", 255), PIC("sc2203cel", 136), PIC("sc2204cel", 1005),
  PIC("sc2205cel", 121),
  PIC("sc2206cel", 345), PIC("sc2207cel", 151), PIC("sc2208cel", 285), PIC("sc2209cel", 316),
  PIC("sc2210cel", 285),
  PIC("sc2211cel", 316), PIC("sc2212cel", 285), PIC("sc2213cel", 316), PIC("sc2214cel", 285),
  PIC("sc2215cel", 316),
  PIC("sc2216cel", 345), PIC("sc2217cel", 346), PIC("sc2218cel", 345), PIC("sc2219cel", 346),
  PIC("sc2220cel", 345),
  PIC("sc2221cel", 331), PIC("sc2222cel", 480), PIC("sc2223cel", 376), PIC("sc2224cel", 375),
  PIC("sc2225cel", 376),
  PIC("sc2226cel", 75),  PIC("sc2227cel", 76),  PIC("sc2228cel", 105), PIC("sc2229cel", 106),
  PIC("sc2232cel", 645),
  PIC("sc2231cel", 646), PIC("sc2230cel", 645), PIC("sc2233cel", 830)
};

static PicData dsc22[33] =
{
  PIC("ss2201cel", 300), PIC("ss2202cel", 255), PIC("ss2203cel", 136), PIC("ss2204cel", 1005),
  PIC("ss2205cel", 121),
  PIC("ss2206cel", 345), PIC("ss2207cel", 151), PIC("ss2208cel", 285), PIC("ss2209cel", 316),
  PIC("ss2210cel", 285),
  PIC("ss2211cel", 316), PIC("ss2212cel", 285), PIC("ss2213cel", 316), PIC("ss2214cel", 285),
  PIC("ss2215cel", 316),
  PIC("ss2216cel", 345), PIC("ss2217cel", 346), PIC("ss2218cel", 345), PIC("ss2219cel", 346),
  PIC("ss2220cel", 345),
  PIC("ss2221cel", 331), PIC("ss2222cel", 480), PIC("ss2223cel", 376), PIC("ss2224cel", 375),
  PIC("ss2225cel", 376),
  PIC("ss2226cel", 75),  PIC("ss2227cel", 76),  PIC("ss2228cel", 105), PIC("ss2229cel", 106),
  PIC("ss2232cel", 645),
  PIC("ss2231cel", 646), PIC("ss2230cel", 645), PIC("ss2233cel", 830)
};

static PicData dsc23[29] =
{
  PIC("sc2301cel", 270), PIC("sc2302cel", 252), PIC("sc2303cel", 267), PIC("sc2304cel", 252),
  PIC("sc2305cel", 312),
  PIC("sc2306cel", 132), PIC("sc2307cel", 162), PIC("sc2308cel", 402), PIC("sc2309cel", 372),
  PIC("sc2310cel", 402),
  PIC("sc2311cel", 282), PIC("sc2312cel", 222), PIC("sc2313cel", 222), PIC("sc2314cel", 222),
  PIC("sc2315cel", 222),
  PIC("sc2316cel", 222), PIC("sc2317cel", 222), PIC("sc2318cel", 222), PIC("sc2319cel", 222),
  PIC("sc2320cel", 162),
  PIC("sc2321cel", 282), PIC("sc2322cel", 822), PIC("sc2323cel", 882), PIC("sc2324cel", 642),
  PIC("sc2325cel", 342),
  PIC("sc2326cel", 462), PIC("sc2327cel", 462), PIC("sc2328cel", 462), PIC("sc2329cel", 345)
};

static PicData dsc24[50] =
{
  PIC("sc2401cel", 120), PIC("sc2402cel", 133), PIC("sc2403cel", 104), PIC("sc2404cel", 103),
  PIC("sc2405cel", 104),
  PIC("sc2406cel", 103), PIC("sc2407cel", 134), PIC("sc2408cel", 103), PIC("sc2409cel", 134),
  PIC("sc2410cel", 103),
  PIC("sc2412cel", 134), PIC("sc2413cel", 103), PIC("sc2414cel", 134), PIC("sc2415cel", 103),
  PIC("sc2416cel", 134),
  PIC("sc2417cel", 103), PIC("sc2418cel", 134), PIC("sc2419cel", 103), PIC("sc2420cel", 134),
  PIC("sc2422cel", 103),
  PIC("sc2423cel", 134), PIC("sc2424cel", 103), PIC("sc2425cel", 134), PIC("sc2426cel", 118),
  PIC("sc2427cel", 43),
  PIC("sc2428cel", 104), PIC("sc2429cel", 103), PIC("sc2430cel", 104), PIC("sc2431cel", 103),
  PIC("sc2433cel", 104),
  PIC("sc2434cel", 133), PIC("sc2435cel", 104), PIC("sc2436cel", 133), PIC("sc2437cel", 104),
  PIC("sc2438cel", 133),
  PIC("sc2439cel", 179), PIC("sc2440cel", 193), PIC("sc2411cel", 179), PIC("sc2443cel", 103),
  PIC("sc2441cel", 104),
  PIC("sc2442cel", 133), PIC("sc2444cel", 164), PIC("sc2445cel", 163), PIC("sc2446cel", 164),
  PIC("sc2447cel", 163),
  PIC("sc2448cel", 194), PIC("sc2449cel", 163), PIC("sc2450cel", 194), PIC("sc2451cel", 163),
  PIC("sc2452cel", 195)
};

static PicData dsc25[45] =
{
  PIC("sc2501cel", 120), PIC("sc2502cel", 136), PIC("sc2503cel", 196),  PIC("sc2504cel", 106),
  PIC("sc2505cel", 106),
  PIC("sc2506cel", 136), PIC("sc2507cel", 106), PIC("sc2508cel", 136),  PIC("sc2509cel", 136),
  PIC("sc2510cel", 106),
  PIC("sc2511cel", 136), PIC("sc2512cel", 106), PIC("sc2513cel", 136),  PIC("sc2514cel", 136),
  PIC("sc2515cel", 136),
  PIC("sc2516cel", 106), PIC("sc2517cel", 136), PIC("sc2518cel", 136),  PIC("sc2519cel", 120),
  PIC("sc2520cel", 106),
  PIC("sc2521cel", 136), PIC("sc2522cel", 136), PIC("sc2523cel", 136),  PIC("sc2524cel", 120),
  PIC("sc2525cel", 106),
  PIC("sc2526cel", 106), PIC("sc2527cel", 136), PIC("sc2528cel", 1020), PIC("sc2529cel", 60),
  PIC("sc2530cel", 586),
  PIC("sc2531cel", 856), PIC("sc2532cel", 286), PIC("sc2533cel", 406),  PIC("sc2534cel", 316),
  PIC("sc2535cel", 286),
  PIC("sc2536cel", 135), PIC("sc2537cel", 151), PIC("sc2538cel", 151),  PIC("sc2539cel", 151),
  PIC("sc2540cel", 151),
  PIC("sc2541cel", 766), PIC("sc2542cel", 181), PIC("sc2543cel", 796),  PIC("sc2544cel", 916),
  PIC("sc2545cel", 870)
};

static PicData dsc26[35] = {PIC("sc2601cel", 165),  PIC("sc2602cel", 236),  PIC("sc2603cel", 656),
                            PIC("sc2604cel", 251),
                            PIC("sc2605cel", 881),  PIC("sc2606cel", 611),  PIC("sc2607cel", 521),
                            PIC("sc2608cel", 281),
                            PIC("sc2609cel", 521),  PIC("sc2610cel", 401),  PIC("sc2635cel", 221),
                            PIC("sc2611cel", 161),
                            PIC("sc2612cel", 131),  PIC("sc2613cel", 221),  PIC("sc2614cel", 371),
                            PIC("sc2615cel", 311),
                            PIC("sc2616cel", 596),  PIC("sc2617cel", 281),  PIC("sc2618cel", 476),
                            PIC("sc2619cel", 1031),
                            PIC("sc2620cel", 1196), PIC("sc2621cel", 806),  PIC("sc2622cel", 836),
                            PIC("sc2623cel", 401),
                            PIC("sc2624cel", 401),  PIC("sc2625cel", 176),  PIC("sc2626cel", 281),
                            PIC("sc2627cel", 236),
                            PIC("sc2628cel", 326),  PIC("sc2629cel", 311),  PIC("sc2630cel", 251),
                            PIC("sc2631cel", 461),
                            PIC("sc2632cel", 1361), PIC("sc2633cel", 1031), PIC("sc2634cel", 1751)};

static PicData dsc27[14] =
{
  PIC("sc2702cel", 480),
  PIC("sc2701cel", 357),
  PIC("sc2703cel", 1243),
  PIC("sc2707cel", 1002),
  PIC("sc2704cel", 1798),
  PIC("sc2705cel", 657),
  PIC("sc2706cel", 568),
  PIC("sc2708cel", 357),
  PIC("sc2709cel", 193),
  PIC("sc2710cel", 192),
  PIC("sc2711cel", 958),
  PIC("sc2712cel", 537),
  PIC("sc2713cel", 463),
  PIC("sc2714cel", 735)
};

static PicData dsc28[15] =
{
  PIC("sc2801cel", 210),
  PIC("sc2802cel", 250),
  PIC("sc2803cel", 250),
  PIC("sc2804cel", 250),
  PIC("sc2805cel", 160),
  PIC("sc2806cel", 85),
  PIC("sc2807cel", 190),
  PIC("sc2808cel", 203),
  PIC("sc2809cel", 790),
  PIC("sc2810cel", 235),
  PIC("sc2811cel", 1133),
  PIC("sc2812cel", 25),
  PIC("sc2813cel", 280),
  PIC("sc2814cel", 430),
  PIC("sc2815cel", 580)
};

static PicData dsc29[5] =
{
  PIC("sc2902cel", 435),
  PIC("sc2903cel", 309),
  PIC("sc2904cel", 159),
  PIC("sc2905cel", 699),
  PIC("sc2907cel", 744)
};

static PicData dsc30[21] = {PIC("sc3001cel", 435), PIC("sc3002cel", 217),  PIC("sc3004cel", 218),
                            PIC("sc3003cel", 247),
                            PIC("sc3005cel", 218), PIC("sc3006cel", 217),  PIC("sc3007cel", 878),
                            PIC("sc3008cel", 742),
                            PIC("sc3009cel", 353), PIC("sc3010cel", 1057), PIC("sc3011cel", 1118),
                            PIC("sc3012cel", 187),
                            PIC("sc3013cel", 218), PIC("sc3014cel", 217),  PIC("sc3015cel", 188),
                            PIC("sc3016cel", 217),
                            PIC("sc3017cel", 218), PIC("sc3018cel", 187),  PIC("sc3019cel", 218),
                            PIC("sc3020cel", 217),
                            PIC("sc3021cel", 188)};

static PicData dsc31[17] =
{
  PIC("sc3101cel", 255),
  PIC("sc3102cel", 252),
  PIC("sc3103cel", 118),
  PIC("sc3104cel", 852),
  PIC("sc3105cel", 1243),
  PIC("sc3106cel", 462),
  PIC("sc3107cel", 673),
  PIC("sc3108cel", 732),
  PIC("sc3109cel", 613),
  PIC("sc3110cel", 1272),
  PIC("sc3111cel", 523),
  PIC("sc3112cel", 792),
  PIC("sc3116cel", 1543),
  PIC("sc3113cel", 762),
  PIC("sc3114cel", 763),
  PIC("sc3102cel", 1362),
  PIC("sc3115cel", 1485)
};

static PicData dsc32[23] = {PIC("sc3201cel", 210), PIC("sc3202cel", 220), PIC("sc3203cel", 220),
                            PIC("sc3204cel", 220),
                            PIC("sc3205cel", 220), PIC("sc3206cel", 220), PIC("sc3207cel", 220),
                            PIC("sc3208cel", 220),
                            PIC("sc3209cel", 220), PIC("sc3210cel", 220), PIC("sc3211cel", 220),
                            PIC("sc3212cel", 220),
                            PIC("sc3213cel", 220), PIC("sc3216cel", 220), PIC("sc3214cel", 220),
                            PIC("sc3215cel", 220),
                            PIC("sc3217cel", 220), PIC("sc3218cel", 220), PIC("sc3221cel", 220),
                            PIC("sc3224cel", 220),
                            PIC("sc3223cel", 220), PIC("sc3222cel", 220), PIC("sc3220cel", 200)};

static ubyte *gBackPic;
static CCBPtr Help;
static CCBPtr MainScene;
static CCBPtr Choice[3] = {0, 0, 0};
static int32 stepback;
static uchar RootName[15]  = "boot/tuntest";
static uint8 ScoreText[20] = "";


static
int
_str_equal(const uchar *a_,
           const char  *b_);


static
void
_copy_name(uchar       *dst_,
           const uchar *src_,
           int32        max_);


static
void
_set_option(uint8      *Option_,
            const char *name_);


static
void
_set_option_adjust(uint8      *Option_,
                   const char *name_,
                   int32       delta_);


static
int32
_back_pic_size(ScreenContext *sc_);


static
int32
_current_screen(ScreenContext *sc_);


static
void
_set_quad(Point quad[4],
          Coord left_,
          Coord top_,
          Coord right_,
          Coord bottom_);


static
void
_center_cel(CCB *cel_);


static
uint32
_picture_table_fields(PicDataPtr data_,
                      int32      count_);


static
int32
_draw_decision_screen(ScreenContext *sc_,
                      Item           vramIOReq_,
                      int32          showHelp_);


static
int
_str_equal(const uchar *a_,
           const char  *b_)
{
  while(*a_ && *b_)
    {
      if(*a_ != (uchar) * b_)
        return 0;
      a_++;
      b_++;
    }
  return *a_ == 0 && *b_ == 0;
}


static
void
_copy_name(uchar       *dst_,
           const uchar *src_,
           int32        max_)
{
  int32 i;

  if(!dst_ || max_ <= 0)
    return;
  i = 0;
  while(src_ && src_[i] && i < max_ - 1)
    {
      dst_[i] = src_[i];
      i++;
    }
  dst_[i] = 0;
}


static
void
_set_option(uint8      *Option_,
            const char *name_)
{
  _copy_name(Option_, (const uchar *)name_, 15);
}


static
void
_set_option_adjust(uint8      *Option_,
                   const char *name_,
                   int32       delta_)
{
  _set_option(Option_, name_);
  point += delta_;
}


static
int32
_back_pic_size(ScreenContext *sc_)
{
  if(sc_ && sc_->sc_nFrameBufferPages > 0 && GrafBase)
    {
      return sc_->sc_nFrameBufferPages * GrafBase->gf_VRAMPageSize;
    }
  return BULLETHOLE_SCREEN_W * BULLETHOLE_SCREEN_H * 2;
}


static
int32
_current_screen(ScreenContext *sc_)
{
  int32 screen;

  if(!sc_)
    return 0;
  screen = sc_->sc_curScreen;
  if(screen < 0 || screen >= 6)
    return 0;
  return screen;
}


static
void
_set_quad(Point quad[4],
          Coord left_,
          Coord top_,
          Coord right_,
          Coord bottom_)
{
  quad[0].pt_X = left_;
  quad[0].pt_Y = top_;
  quad[1].pt_X = right_;
  quad[1].pt_Y = top_;
  quad[2].pt_X = right_;
  quad[2].pt_Y = bottom_;
  quad[3].pt_X = left_;
  quad[3].pt_Y = bottom_;
}


static
void
_center_cel(CCB *cel_)
{
  Point quad[4];
  Coord left;
  Coord top;

  if(!cel_)
    return;
  left = (BULLETHOLE_SCREEN_W - cel_->ccb_Width) / 2;
  top  = (BULLETHOLE_SCREEN_H - cel_->ccb_Height) / 2;
  _set_quad(quad, left, top, left + cel_->ccb_Width, top + cel_->ccb_Height);
  MapCel(cel_, quad);
}


Boolean
InitBackPic(ScreenContext *sc_,
            Item           VRAMIOReq_)
{
  int32 size;
  uint32 memType;
  Err err;

  if(!sc_ || VRAMIOReq_ <= 0)
    return 0;
  if(!GrafBase)
    return 0;
  size    = _back_pic_size(sc_);
  memType = GETBANKBITS(GrafBase->gf_ZeroPage) | BACKPIC_MEMTYPE;
  gBackPic = (ubyte *)AllocMem(size, memType);
  if(!gBackPic)
    return 0;
  err = SetVRAMPages(VRAMIOReq_, gBackPic, 0, sc_->sc_nFrameBufferPages, -1);
  if(err < 0)
    {
      FreeMem(gBackPic, size);
      gBackPic = 0;
      return 0;
    }
  return 1;
}


int32
CopyBackPic(ScreenContext *TheScreen_,
            Bitmap        *bitmap_,
            Item           VRAMIOReq_)
{
  if(TheScreen_ == NULL || bitmap_ == NULL || gBackPic == NULL)
    {
      return -1;
    }

  return CopyVRAMPages(
    VRAMIOReq_,
    bitmap_->bm_Buffer,
    gBackPic,
    TheScreen_->sc_nFrameBufferPages,
    (uint32) - 1);
}


Boolean
InitPicture(ScreenContext *TheScreen_)
{
  Item vramIOReq;
  Err err;
  int32 screen;
  Bitmap *bitmap;

  if(!TheScreen_)
    return 0;
  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    return 0;

  screen = _current_screen(TheScreen_);
  bitmap = TheScreen_->sc_Bitmaps[screen];
  if(bitmap)
    {
      err = SetVRAMPages(vramIOReq, bitmap->bm_Buffer, 0, TheScreen_->sc_nFrameBufferPages, -1);
      if(err < 0)
        {
          DeleteItem(vramIOReq);
          return 0;
        }
    }

  TheScreen_->sc_curScreen = 1 - screen;
  screen                  = _current_screen(TheScreen_);
  bitmap = TheScreen_->sc_Bitmaps[screen];
  if(bitmap)
    {
      err = SetVRAMPages(vramIOReq, bitmap->bm_Buffer, 0, TheScreen_->sc_nFrameBufferPages, -1);
      if(err < 0)
        {
          DeleteItem(vramIOReq);
          return 0;
        }
    }

  TheScreen_->sc_curScreen = 1 - screen;
  screen                  = _current_screen(TheScreen_);
  if(TheScreen_->sc_Screens[screen])
    DisplayScreen(TheScreen_->sc_Screens[screen], 0);
  if(!InitBackPic(TheScreen_, vramIOReq))
    {
      DeleteItem(vramIOReq);
      return 0;
    }
  TheScreen_->sc_curScreen = 0;
  err = DeleteItem(vramIOReq);
  return 1;
}


int32
DisplayBarnDoorOpen(ScreenContext *sc_,
                    Item           vramIOReq_,
                    CCB           *underCel_,
                    CCB           *doorCel_)
{
  Item vblIOReq;
  Point quad[4];
  Bitmap *bitmap;
  int32 screen;
  int32 edge;
  int32 result;
  int32 waitResult;

  if(!sc_)
    return -1;

  result   = 1;
  vblIOReq = GetVBLIOReq();
  if(vblIOReq < 0)
    return -1;

  for(edge = 160; edge >= 0; edge -= 10)
    {
      sc_->sc_curScreen = 1 - _current_screen(sc_);
      screen           = _current_screen(sc_);
      bitmap           = sc_->sc_Bitmaps[screen];
      if(!bitmap || CopyVRAMPages(vramIOReq_, bitmap->bm_Buffer, gBackPic,
                                  sc_->sc_nFrameBufferPages,
                                  (uint32) - 1) != 0)
        {
          result = -1;
          goto cleanup;
        }

      if(doorCel_)
        {
          _set_quad(quad, edge, 0, BULLETHOLE_SCREEN_W - edge, BULLETHOLE_SCREEN_H);
          MapCel(doorCel_, quad);
        }
      if(underCel_)
        DrawScreenCels(sc_->sc_Screens[screen], underCel_);
      if(doorCel_)
        DrawScreenCels(sc_->sc_Screens[screen], doorCel_);
      DisplayScreen(sc_->sc_Screens[screen], 0);
      PDWTSceneControlPresent(screen);
      waitResult = PDWTSceneControlWaitFields(vblIOReq, 1);
      if(waitResult != PDWT_SCENE_CONTROL_CONTINUE)
        {
          result = waitResult;
          goto cleanup;
        }
    }

cleanup:
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


int32
DisplayCenterMerge(ScreenContext *sc_,
                   Item           vramIOReq_,
                   CCB           *mergeCel_,
                   CCB           *underCel_)
{
  Item vblIOReq;
  Point quad[4];
  Bitmap *bitmap;
  int32 screen;
  int32 spread;
  int32 halfHeight;
  int32 result;
  int32 waitResult;

  if(!sc_)
    return -1;

  result   = 1;
  vblIOReq = GetVBLIOReq();
  if(vblIOReq < 0)
    return -1;

  for(spread = 160; spread >= 0; spread -= 5)
    {
      sc_->sc_curScreen = 1 - _current_screen(sc_);
      screen           = _current_screen(sc_);
      bitmap           = sc_->sc_Bitmaps[screen];
      if(!bitmap || CopyVRAMPages(vramIOReq_, bitmap->bm_Buffer, gBackPic,
                                  sc_->sc_nFrameBufferPages,
                                  (uint32) - 1) != 0)
        {
          result = -1;
          goto cleanup;
        }

      if(mergeCel_)
        {
          halfHeight = (spread * 3) / 4;
          _set_quad(quad, 160 - spread, 120 - halfHeight, 160 + spread, 120 + halfHeight);
          MapCel(mergeCel_, quad);
        }
      if(underCel_)
        DrawScreenCels(sc_->sc_Screens[screen], underCel_);
      if(mergeCel_)
        DrawScreenCels(sc_->sc_Screens[screen], mergeCel_);
      DisplayScreen(sc_->sc_Screens[screen], 0);
      PDWTSceneControlPresent(screen);
      waitResult = PDWTSceneControlWaitFields(vblIOReq, 1);
      if(waitResult != PDWT_SCENE_CONTROL_CONTINUE)
        {
          result = waitResult;
          goto cleanup;
        }
    }

cleanup:
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


void
PutNumXY(ScreenContext *TheScreen_,
         int32          score_,
         Coord          x_,
         Coord          y_)
{
  GrafCon gcon;

  sprintf((char *)ScoreText, "SCORES:%d", score_);
  gcon.gc_PenX = x_;
  gcon.gc_PenY = y_;
  DrawText8(&gcon, TheScreen_->sc_BitmapItems[TheScreen_->sc_curScreen], ScoreText);
}


int32
bullethole(CCB           *backCel_,
           int32          remaining_,
           Item           vblIOReq_,
           Item           vramIOReq_,
           ScreenContext *sc_)
{
  CCB    *holeCel;
  Bitmap *bitmap;
  Item bitmapItem;
  TagArg bitmapTags[4];
  Item screenItem;
  ubyte  *tempBuffer;
  int32 frame;
  int32 delay;
  int32 waitResult;
  int32 result;
  int32 curScreen;
  int32 dx;
  int32 dy;
  int32 dir;
  int32 phase;
  uint32 randomValue;

  if(!backCel_ || !sc_)
    return -1;

  tempBuffer = (ubyte *)AllocMem(BULLETHOLE_TEMP_SIZE, BULLETHOLE_TEMP_MEMTYPE);
  if(!tempBuffer)
    return -1;

  bitmapTags[0].ta_Tag = BULLETHOLE_BMTAG_WIDTH;
  bitmapTags[0].ta_Arg = (void *)BULLETHOLE_SCREEN_W;
  bitmapTags[1].ta_Tag = BULLETHOLE_BMTAG_HEIGHT;
  bitmapTags[1].ta_Arg = (void *)BULLETHOLE_SCREEN_H;
  bitmapTags[2].ta_Tag = BULLETHOLE_BMTAG_BUFFER;
  bitmapTags[2].ta_Arg = tempBuffer;
  bitmapTags[3].ta_Tag = 0;
  bitmapTags[3].ta_Arg = 0;

  bitmapItem = CreateItem(BULLETHOLE_BITMAP_NODE, bitmapTags);
  if(bitmapItem < 0)
    {
      FreeMem(tempBuffer, BULLETHOLE_TEMP_SIZE);
      return -1;
    }
  bitmap = (Bitmap *)LookupItem(bitmapItem);
  if(!bitmap)
    {
      if(bitmapItem > 0)
        {
          DeleteItem(bitmapItem);
        }
      FreeMem(tempBuffer, BULLETHOLE_TEMP_SIZE);
      return -1;
    }

  holeCel = LoadCel(BULLETHOLE_CEL_PATH, MEMTYPE_CEL);
  if(!holeCel)
    {
      if(bitmapItem > 0)
        {
          DeleteItem(bitmapItem);
        }
      FreeMem(tempBuffer, BULLETHOLE_TEMP_SIZE);
      return -1;
    }

  randomValue       = (uint32)rand();
  holeCel->ccb_XPos = (Coord)((randomValue >> 16) * BULLETHOLE_RANDOM_X_SCALE);
  randomValue       = (uint32)rand();
  holeCel->ccb_YPos = (Coord)((randomValue >> 16) * BULLETHOLE_RANDOM_Y_SCALE);

  backCel_->ccb_NextPtr = holeCel;
  backCel_->ccb_Flags &= ~CCB_LAST;
  holeCel->ccb_NextPtr = (CCB *)0;
  holeCel->ccb_Flags |= CCB_LAST;

  curScreen = sc_->sc_curScreen;
  if(curScreen < 0 || curScreen >= 6)
    curScreen = 0;
  screenItem = sc_->sc_Screens[curScreen];
  if(screenItem)
    DrawScreenCels(screenItem, backCel_);
  if(screenItem)
    {
      DisplayScreen(screenItem, 0);
      PDWTSceneControlPresent(curScreen);
    }
  if(bitmapItem)
    DrawCels(bitmapItem, backCel_);

  frame = 0;
  dx    = 0;
  dy    = 0;
  result = 1;
  while(remaining_ > 0)
    {
      frame++;
      curScreen = sc_->sc_curScreen;
      if(curScreen < 0 || curScreen >= 6)
        curScreen = 0;

      screenItem = sc_->sc_Screens[curScreen];
      if(bitmap)
        {
          waitResult = CopyBackPic(sc_, bitmap, vramIOReq_);
          if(waitResult < 0)
            {
              result = waitResult;
              break;
            }
        }

      backCel_->ccb_Flags     = BULLETHOLE_BG_FLAGS;
      backCel_->ccb_Width     = BULLETHOLE_SCREEN_W;
      backCel_->ccb_Height    = BULLETHOLE_SCREEN_H;
      backCel_->ccb_XPos      = 0;
      backCel_->ccb_YPos      = 0;
      backCel_->ccb_HDX       = 0x00100000L;
      backCel_->ccb_HDY       = 0;
      backCel_->ccb_VDX       = 0;
      backCel_->ccb_VDY       = 0x00010000L;
      backCel_->ccb_HDDX      = 0;
      backCel_->ccb_HDDY      = 0;
      backCel_->ccb_PIXC      = BULLETHOLE_PIXC;
      backCel_->ccb_PRE0      = ((BULLETHOLE_SCREEN_H - 1) << 6) | 0x16;
      backCel_->ccb_PRE1      = (BULLETHOLE_SCREEN_W - 1) | 0x013C0000UL | 0x00020800UL;
      backCel_->ccb_SourcePtr = bitmap ? (CelData *)bitmap->bm_Buffer : (CelData *)0;

      delay = 0;
      phase = frame % 5;
      if(phase == 0)
        {
          randomValue       = (uint32)rand();
          holeCel->ccb_XPos = (Coord)((randomValue >> 16) * BULLETHOLE_RANDOM_X_SCALE);
          randomValue       = (uint32)rand();
          holeCel->ccb_YPos = (Coord)((randomValue >> 16) * BULLETHOLE_RANDOM_Y_SCALE);
          delay             = 8;
        }
      else if(phase == 1)
        {
          dir = (int32)((uint32)rand() & 7UL);
          switch(dir)
            {
            case 0:
              dx = 0x000C0000L;
              dy = 0x00090000L;
              break;
            case 1:
              dx = 0x00090000L;
              dy = 0x000C0000L;
              break;
            case 2:
              dx = -0x000C0000L;
              dy = 0x00090000L;
              break;
            case 3:
              dx = -0x00090000L;
              dy = 0x000C0000L;
              break;
            case 4:
              dx = -0x000C0000L;
              dy = -0x00090000L;
              break;
            case 5:
              dx = -0x00090000L;
              dy = -0x000C0000L;
              break;
            case 6:
              dx = 0x000C0000L;
              dy = -0x00090000L;
              break;
            default:
              dx = 0x00090000L;
              dy = -0x000C0000L;
              break;
            }
          holeCel->ccb_XPos += dx;
          holeCel->ccb_YPos += dy;
          delay = 3;
        }
      else
        {
          holeCel->ccb_XPos += dx;
          holeCel->ccb_YPos += dy;
          delay = 3;
        }

      if(screenItem)
        DrawScreenCels(screenItem, backCel_);
      if(screenItem)
        {
          DisplayScreen(screenItem, 0);
          PDWTSceneControlPresent(curScreen);
        }
      if(bitmapItem)
        DrawCels(bitmapItem, backCel_);
      if(delay > remaining_)
        delay = remaining_;
      waitResult = PDWTSceneControlWaitFields(vblIOReq_, delay);
      if(waitResult != PDWT_SCENE_CONTROL_CONTINUE)
        {
          result = waitResult;
          break;
        }
      remaining_ -= delay;
    }

  backCel_->ccb_NextPtr = (CCB *)0;
  backCel_->ccb_Flags |= CCB_LAST;
  UnloadCel(holeCel);
  FreeMem(tempBuffer, BULLETHOLE_TEMP_SIZE);
  if(bitmapItem > 0)
    {
      DeleteItem(bitmapItem);
    }
  return result;
}


int32
decSpeech(DecDataPtr choice_)
{
  uchar name[32];
  SoundFilePlayer *player;
  int32 signalIn;
  int32 signalNeeded;
  int32 err;
  int32 closeErr;

  if(!choice_)
    return -1;

  sprintf((char *)name, "$boot/tuntest/dec/%s", choice_->name);

  player = OpenSoundFile((char *)name, 2, 0x8000);
  if(!player)
    return -1;

  err = StartSoundFile(player, 0x4000);
  if(err < 0)
    goto cleanup;

  signalIn     = 0;
  signalNeeded = 0;
  do
    {
      if(signalNeeded != 0)
        {
          signalIn = WaitSignal((uint32)signalNeeded);
        }
      err = ServiceSoundFile(player, signalIn, &signalNeeded);
      if(err < 0)
        {
          goto cleanup;
        }
    } while(signalNeeded != 0);

cleanup:
  closeErr = CloseSoundFile(player);
  if(err < 0)
    return -1;
  if(closeErr < 0)
    return -1;
  return 0;
}


PicDataPtr
ReadPictureData(uint8 *name_,
                int32 *count_)
{
  uchar sceneNum[3];
  int32 scene;

  sceneNum[0] = name_[3];
  sceneNum[1] = name_[4];
  sceneNum[2] = 0;
  scene       = atoi((char *)sceneNum);

  switch(scene)
    {
    case 15:
      *count_ = 17;
      return dsc15;
    case 16:
      *count_ = 9;
      return dsc16;
    case 17:
      *count_ = 14;
      return dsc17;
    case 18:
      *count_ = 20;
      return dsc18;
    case 20:
      *count_ = 12;
      return dsc20;
    case 21:
      *count_ = 22;
      return dsc21;
    case 22:
      *count_ = 33;
      if(name_[0] == 'd')
        return dsc22;
      return ssc22;
    case 23:
      *count_ = 29;
      return dsc23;
    case 24:
      *count_ = 50;
      return dsc24;
    case 25:
      *count_ = 45;
      return dsc25;
    case 26:
      *count_ = 35;
      return dsc26;
    case 27:
      *count_ = 14;
      return dsc27;
    case 28:
      *count_ = 15;
      return dsc28;
    case 29:
      *count_ = 5;
      return dsc29;
    case 30:
      *count_ = 21;
      return dsc30;
    case 31:
      *count_ = 17;
      return dsc31;
    case 32:
      *count_ = 23;
      return dsc32;
    }
  *count_ = 0;
  return (PicDataPtr)0;
}


static
uint32
_picture_table_fields(PicDataPtr data_,
                      int32      count_)
{
  uint32 total;
  int32 i;

  total = 0;
  for(i = 0; i < count_; i++)
    {
      total += (uint32)data_[i].time;
    }
  return total;
}


int32
showpicture(ScreenContext *TheScreen_,
            uint8         *Nscene_)
{
  uchar dataName[50];
  uchar path[50];
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  PicDataPtr data;
  Bitmap            *bitmap;
  Item vramIOReq;
  Item vblIOReq;
  int32 count;
  int32 i;
  int32 screen;
  int32 scheduleFields;
  int32 active;
  int32 sc25Scene;
  int32 eventOpen;
  int32 eventResult;
  int32 mainSceneLoaded;
  int32 audioComplete;
  int32 controlOpen;
  int32 audioResult;
  int32 sceneResult;
  int32 result;

  if(!TheScreen_ || !Nscene_)
    return -1;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  vramIOReq       = 0;
  vblIOReq        = 0;
  eventOpen       = 0;
  mainSceneLoaded = 0;
  audioComplete   = 0;
  controlOpen     = 0;
  result          = -1;

  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    goto cleanup;
  vblIOReq = GetVBLIOReq();
  if(vblIOReq < 0)
    goto cleanup;
  count = 0;

  if(strcmp((char *)Nscene_, "sc22") == 0 && secretpass)
    {
      sprintf((char *)dataName, "s%s", Nscene_);
    }
  else
    {
      sprintf((char *)dataName, "d%s", Nscene_);
    }

  data = ReadPictureData(dataName, &count);
  if(!data)
    goto cleanup;

  eventResult = InitEventUtility(1, 0, 1);
  if(eventResult != 0)
    {
      result = eventResult < 0 ? eventResult : -1;
      goto cleanup;
    }
  eventOpen = 1;

  sprintf((char *)dataName, "$boot/tuntest/%s/%s.aiff", Nscene_, Nscene_);
  audioResult = DecisionAudioStartWithBuffers(
    &sceneAudio,
    dataName,
    STORY_AUDIO_BUFFER_COUNT,
    STORY_AUDIO_BUFFER_SIZE,
    STORY_AUDIO_AMPLITUDE);
  if(audioResult < 0)
    {
      result = audioResult;
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, Nscene_, _picture_table_fields(data, count));

  TheScreen_->sc_curScreen = 0;
  active    = 1;
  sc25Scene = strcmp((char *)Nscene_, "sc25") == 0;
  sceneResult = PDWTSceneControlBegin(
    &sceneControl,
    TheScreen_,
    vramIOReq,
    vblIOReq,
    &sceneAudio,
    &sceneClock);
  if(sceneResult < 0)
    {
      result = sceneResult;
      goto cleanup;
    }
  controlOpen = 1;
  if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
    {
      stepback = 1;
      active   = 0;
    }
  else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
    {
      active = 0;
    }

  for(i = 0; i < count && active; i++)
    {
      sprintf((char *)path, "$boot/tuntest/%s/%s", Nscene_, data[i].name);
      MainScene = LoadCel((char *)path, MEMTYPE_CEL);
      if(!MainScene)
        goto cleanup;
      mainSceneLoaded        = 1;
      MainScene->ccb_NextPtr = (CCB *)0;
      MainScene->ccb_Flags |= CCB_LAST;
      _center_cel(MainScene);

      screen = _current_screen(TheScreen_);
      bitmap = TheScreen_->sc_Bitmaps[screen];
      if(bitmap)
        {
          sceneResult = CopyBackPic(TheScreen_, bitmap, vramIOReq);
          if(sceneResult < 0)
            {
              result = sceneResult;
              goto cleanup;
            }
        }

      scheduleFields = data[i].time;
      if(sc25Scene && (data[i].time & 1))
        {
          sceneResult = bullethole(MainScene, scheduleFields, vblIOReq, vramIOReq, TheScreen_);
        }
      else if(i == 0)
        {
          sceneResult = DisplayBarnDoorOpen(TheScreen_, vramIOReq, 0, MainScene);
        }
      else
        {
          sceneResult = PDWT_SCENE_CONTROL_CONTINUE;
          if(TheScreen_->sc_Screens[screen])
            {
              DrawScreenCels(TheScreen_->sc_Screens[screen], MainScene);
              DisplayScreen(TheScreen_->sc_Screens[screen], 0);
              PDWTSceneControlPresent(screen);
            }
        }

      if(sceneResult < 0)
        {
          result = sceneResult;
          goto cleanup;
        }
      if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
        {
          stepback = 1;
          active   = 0;
        }
      else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
        {
          active = 0;
        }

      TheScreen_->sc_curScreen = 1 - _current_screen(TheScreen_);
      if(active)
        {
          sceneResult = PDWTSceneControlWaitClock(&sceneClock, vblIOReq, scheduleFields);
          if(sceneResult < 0)
            {
              result = sceneResult;
              goto cleanup;
            }
          if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
            {
              stepback = 1;
              active   = 0;
            }
          else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
            {
              active = 0;
            }
        }
      if(active && i == count - 1)
        {
          sceneResult = PDWTSceneControlWaitAudio(&sceneAudio, vblIOReq);
          if(sceneResult < 0)
            {
              result = sceneResult;
              goto cleanup;
            }
          if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
            {
              stepback = 1;
              active   = 0;
            }
          else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
            {
              active = 0;
            }
          else
            {
              audioComplete = 1;
            }
        }
      if(active && i == count - 1)
        {
          sceneResult = DisplayCenterMerge(TheScreen_, vramIOReq, MainScene, 0);
          if(sceneResult < 0)
            {
              result = sceneResult;
              goto cleanup;
            }
          if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
            {
              stepback = 1;
              active   = 0;
            }
          else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
            {
              active = 0;
            }
        }
      UnloadCel(MainScene);
      MainScene       = 0;
      mainSceneLoaded = 0;
    }

  if(active && !audioComplete)
    {
      sceneResult = PDWTSceneControlWaitAudio(&sceneAudio, vblIOReq);
      if(sceneResult < 0)
        {
          result = sceneResult;
          goto cleanup;
        }
      if(sceneResult == PDWT_SCENE_CONTROL_STEP_BACK)
        {
          stepback = 1;
          active   = 0;
        }
      else if(sceneResult == PDWT_SCENE_CONTROL_SKIP)
        {
          active = 0;
        }
    }

  PDWTSceneControlEnd(&sceneControl);
  controlOpen = 0;
  screen = _current_screen(TheScreen_);
  bitmap = TheScreen_->sc_Bitmaps[screen];
  if(bitmap)
    {
      sceneResult = CopyBackPic(TheScreen_, bitmap, vramIOReq);
      if(sceneResult < 0)
        {
          result = sceneResult;
          goto cleanup;
        }
    }
  result = 1;

cleanup:
  if(controlOpen)
    {
      PDWTSceneControlEnd(&sceneControl);
    }
  if(mainSceneLoaded && MainScene)
    {
      UnloadCel(MainScene);
      MainScene = 0;
    }
  audioResult = DecisionAudioStop(&sceneAudio);
  if(audioResult < 0 && result >= 0)
    {
      result = audioResult;
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      eventResult = KillEventUtility();
      if(eventResult != 0 && result >= 0)
        {
          result = eventResult < 0 ? eventResult : -1;
        }
    }
  return result;
}


DecDataPtr
ReadDecisionData(uint8 *name_,
                 int32 *count_)
{
  uchar sceneNum[3];
  int32 scene;

  sceneNum[0] = name_[3];
  sceneNum[1] = name_[4];
  sceneNum[2] = 0;
  scene       = atoi((char *)sceneNum);

  switch(scene)
    {
    case 13:
      *count_ = 3;
      return dec13;
    case 16:
      *count_ = 2;
      return dec16;
    case 18:
      *count_ = 2;
      return dec18;
    case 20:
      *count_ = 2;
      return dec20;
    case 22:
      *count_ = 2;
      return dec22;
    case 23:
      *count_ = 2;
      return dec23;
    case 25:
      *count_ = 2;
      return dec25;
    case 26:
      *count_ = 2;
      return dec26;
    case 28:
      *count_ = 2;
      return dec28;
    case 29:
      *count_ = 2;
      return dec29;
    case 30:
      *count_ = 3;
      return dec30;
    case 31:
      *count_ = 2;
      return dec31;
    }
  *count_ = 0;
  return (DecDataPtr)0;
}


static
int32
_draw_decision_screen(ScreenContext *sc_,
                      Item           vramIOReq_,
                      int32          showHelp_)
{
  Bitmap *bitmap;
  int32 result;
  int32 screen;

  sc_->sc_curScreen = 1 - _current_screen(sc_);
  screen           = _current_screen(sc_);
  bitmap           = sc_->sc_Bitmaps[screen];
  if(bitmap)
    {
      result = CopyBackPic(sc_, bitmap, vramIOReq_);
      if(result < 0)
        {
          return result;
        }
    }

  if(showHelp_)
    {
      if(sc_->sc_Screens[screen])
        {
          DrawScreenCels(sc_->sc_Screens[screen], Help);
        }
    }
  else
    {
      if(sc_->sc_Screens[screen])
        {
          DrawScreenCels(sc_->sc_Screens[screen], MainScene);
          DrawScreenCels(sc_->sc_Screens[screen], Choice[0]);
        }
      PutNumXY(sc_, point, 15, 215);
    }
  if(sc_->sc_Screens[screen])
    {
      DisplayScreen(sc_->sc_Screens[screen], 0);
    }

  return 0;
}


int32
makedecision(ScreenContext *sc_,
             uint8         *name_)
{
  DecisionAudio decisionAudio;
  uchar path[50];
  DecDataPtr choices;
  Point quad[4];
  Bitmap             *bitmap;
  Item vramIOReq;
  Item vblIOReq;
  ControlPadEventData cped;
  uint32 padBits;
  uint32 lastPadBits;
  uint32 oldPadBits;
  uint32 input;
  uint32 filteredPad;
  int32 count;
  int32 selected;
  int32 voicedSelection;
  int32 finish;
  int32 showHelp;
  int32 screen;
  int32 i;
  int32 eventOpen;
  int32 loadedChoices;
  int32 audioResult;
  int32 waitResult;
  int32 result;

  DecisionAudioInit(&decisionAudio);
  vramIOReq     = 0;
  vblIOReq      = 0;
  eventOpen     = 0;
  loadedChoices = 0;
  result        = -1;
  selected      = 0;
  Help          = 0;
  MainScene     = 0;
  for(i = 0; i < 3; i++)
    {
      Choice[i] = 0;
    }

  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    goto cleanup;
  vblIOReq = GetVBLIOReq();
  if(vblIOReq < 0)
    goto cleanup;

  Help = LoadCel("$boot/tuntest/dec/controlhelp.cel", MEMTYPE_CEL);
  if(!Help)
    goto cleanup;
  Help->ccb_NextPtr = (CCB *)0;
  Help->ccb_Flags |= CCB_LAST;
  _center_cel(Help);

  sprintf((char *)path, "$boot/tuntest/dec/%s.cel", name_);
  MainScene = LoadCel((char *)path, MEMTYPE_CEL);
  if(!MainScene)
    goto cleanup;
  MainScene->ccb_NextPtr = (CCB *)0;
  MainScene->ccb_Flags |= CCB_LAST;
  _center_cel(MainScene);

  count   = 0;
  choices = ReadDecisionData(name_, &count);
  if(!choices || count <= 0)
    goto cleanup;

  if(InitEventUtility(1, 0, 1) != 0)
    goto cleanup;
  eventOpen = 1;

  for(i = 0; i < count; i++)
    {
      Choice[i] = LoadCel("$boot/tuntest/dec/hilite.cel", MEMTYPE_CEL);
      if(!Choice[i])
        goto cleanup;
      loadedChoices++;
      _set_quad(quad, choices[i].x, choices[i].y, choices[i].x + choices[i].w,
                choices[i].y + choices[i].h);
      MapCel(Choice[i], quad);
      Choice[i]->ccb_PIXC = HILITE_PIXC;
    }
  for(i = 1; i < count; i++)
    {
      Choice[i - 1]->ccb_NextPtr = Choice[i];
      Choice[i - 1]->ccb_Flags &= ~CCB_LAST;
    }
  Choice[count - 1]->ccb_NextPtr = (CCB *)0;
  Choice[count - 1]->ccb_Flags |= CCB_LAST;
  Choice[0]->ccb_PIXC = HILITE_SELECTED_PIXC;

  selected        = 0;
  voicedSelection = -1;
  finish          = 1;
  showHelp        = 0;
  lastPadBits     = 0;
  input           = 0;

  result = _draw_decision_screen(sc_, vramIOReq, showHelp);
  if(result < 0)
    {
      goto cleanup;
    }
  sprintf((char *)path, DECISION_SPEECH_PATH_FORMAT, choices[selected].name);
  audioResult = DecisionAudioStart(&decisionAudio, path, DECISION_SPEECH_BUFFER_SIZE,
                                   DECISION_SPEECH_AMPLITUDE);
  if(audioResult < 0)
    goto cleanup;
  voicedSelection = selected;

  while(finish)
    {

      waitResult = WaitVBL(vblIOReq, 1);
      if(waitResult < 0)
        goto cleanup;
      audioResult = DecisionAudioService(&decisionAudio);
      if(audioResult < 0)
        goto cleanup;

      cped.cped_ButtonBits = 0;
      if(GetControlPad(1, 0, &cped) < 0)
        goto cleanup;
      padBits    = cped.cped_ButtonBits;
      oldPadBits = lastPadBits;
      if((padBits ^ lastPadBits) != 0)
        {
          input = padBits;
        }
      else
        {
          filteredPad = padBits & ~0x07000000UL;
          filteredPad &= ~0x00DF0000UL;
          filteredPad &= ~0x0000FF00UL;
          filteredPad &= ~0x000000FFUL;
          if(filteredPad == 0)
            input = 0;
        }

      if(input == RAW_PAD_SELECT)
        {
          finish = 0;
        }
      else if(input == RAW_PAD_UP || input == RAW_PAD_LEFT)
        {
          if(oldPadBits != RAW_PAD_LEFT && oldPadBits != RAW_PAD_UP)
            {
              audioResult = DecisionAudioStop(&decisionAudio);
              if(audioResult < 0)
                goto cleanup;
              Choice[selected]->ccb_PIXC = HILITE_PIXC;
              selected                   = (selected + count - 1) % count;
              Choice[selected]->ccb_PIXC = HILITE_SELECTED_PIXC;
              voicedSelection = -1;
            }
        }
      else if(input == RAW_PAD_DOWN || input == RAW_PAD_RIGHT)
        {
          if(oldPadBits != RAW_PAD_RIGHT && oldPadBits != RAW_PAD_DOWN)
            {
              audioResult = DecisionAudioStop(&decisionAudio);
              if(audioResult < 0)
                goto cleanup;
              Choice[selected]->ccb_PIXC = HILITE_PIXC;
              selected                   = (selected + 1) % count;
              Choice[selected]->ccb_PIXC = HILITE_SELECTED_PIXC;
              voicedSelection = -1;
            }
        }
      else if(input == RAW_PAD_STEPBACK)
        {
          finish   = 0;
          stepback = 1;
        }
      else if(input == RAW_PAD_HELP)
        {
          showHelp = 1;
        }
      else
        {
          showHelp = 0;
        }
      lastPadBits = padBits;

      if(!finish)
        break;

      result = _draw_decision_screen(sc_, vramIOReq, showHelp);
      if(result < 0)
        {
          goto cleanup;
        }
      if(voicedSelection != selected)
        {
          sprintf((char *)path, DECISION_SPEECH_PATH_FORMAT, choices[selected].name);
          audioResult =
            DecisionAudioStart(&decisionAudio, path, DECISION_SPEECH_BUFFER_SIZE,
                               DECISION_SPEECH_AMPLITUDE);
          if(audioResult < 0)
            goto cleanup;
          voicedSelection = selected;
        }
    }

  screen = _current_screen(sc_);
  bitmap = sc_->sc_Bitmaps[screen];
  if(bitmap)
    {
      result = CopyBackPic(sc_, bitmap, vramIOReq);
      if(result < 0)
        {
          goto cleanup;
        }
    }
  result = selected + 1;

cleanup:
  audioResult = DecisionAudioStop(&decisionAudio);
  if(audioResult < 0)
    {
      result = -1;
    }
  if(Help)
    {
      UnloadCel(Help);
      Help = 0;
    }
  if(MainScene)
    {
      UnloadCel(MainScene);
      MainScene = 0;
    }
  for(i = 0; i < loadedChoices; i++)
    {
      if(Choice[i])
        {
          UnloadCel(Choice[i]);
          Choice[i] = 0;
        }
    }
  if(eventOpen && KillEventUtility() != 0)
    {
      result = -1;
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


void
showOption(uint8 *Option_,
           int32 *finish_)
{
  int32 choice;

  if(!Option_)
    return;
  choice = finish_ ? *finish_ : 0;

  if(_str_equal(Option_, "sc15"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec13", 10000);
      else
        _set_option(Option_, "sc16");
      return;
    }
  if(_str_equal(Option_, "sc16"))
    {
      if(stepback == 1)
        _set_option(Option_, "sc15");
      else
        _set_option(Option_, "dec16");
      return;
    }
  if(_str_equal(Option_, "sc17"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec13", 10000);
      else
        _set_option(Option_, "sc18");
      return;
    }
  if(_str_equal(Option_, "sc18"))
    {
      if(stepback == 1)
        _set_option(Option_, "sc17");
      else
        _set_option(Option_, "dec18");
      return;
    }
  if(_str_equal(Option_, "sc20"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec13", 50000);
      else
        _set_option(Option_, "dec20");
      return;
    }
  if(_str_equal(Option_, "sc21"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec20", 90000);
      else
        _set_option(Option_, "sc23");
      return;
    }
  if(_str_equal(Option_, "sc22"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec20", 90000);
      else
        _set_option(Option_, "dec22");
      return;
    }
  if(_str_equal(Option_, "sc23"))
    {
      if(stepback == 1)
        _set_option(Option_, "sc21");
      else
        _set_option(Option_, "dec23");
      return;
    }
  if(_str_equal(Option_, "sc24"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec23", -50000);
      else
        _set_option(Option_, "sc25");
      return;
    }
  if(_str_equal(Option_, "sc25"))
    {
      if(stepback == 1)
        _set_option(Option_, "sc24");
      else
        _set_option(Option_, "dec25");
      return;
    }
  if(_str_equal(Option_, "sc26"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec25", 75000);
      else
        _set_option(Option_, "dec26");
      return;
    }
  if(_str_equal(Option_, "sc27"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec26", 90000);
      else
        _set_option(Option_, "sc29");
      return;
    }
  if(_str_equal(Option_, "sc28"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec23", 50000);
      else
        _set_option(Option_, "dec28");
      return;
    }
  if(_str_equal(Option_, "sc29"))
    {
      if(stepback == 1)
        _set_option(Option_, "sc27");
      else
        _set_option(Option_, "dec29");
      return;
    }
  if(_str_equal(Option_, "sc30"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec29", 20000);
      else
        _set_option(Option_, "dec30");
      return;
    }
  if(_str_equal(Option_, "sc31"))
    {
      if(stepback == 1)
        _set_option_adjust(Option_, "dec29", -90000);
      else
        _set_option(Option_, "dec31");
      return;
    }
  if(_str_equal(Option_, "sc32"))
    {
      if(stepback == 1)
        _set_option(Option_, "dec30");
      else
        _set_option(Option_, "end");
      return;
    }

  if(_str_equal(Option_, "dec13"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc13");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec13");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "sc15", -10000);
          return;
        }
      if(choice == 2)
        {
          _set_option_adjust(Option_, "sc17", -10000);
          return;
        }
      if(choice == 3)
        {
          _set_option_adjust(Option_, "sc20", -50000);
          return;
        }
    }
  if(_str_equal(Option_, "dec16"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc16");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec16");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec13", -20000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec18"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc18");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec18");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec13", -30000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec20"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc20");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec20");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "sc21", -90000);
          return;
        }
      if(choice == 2)
        {
          _set_option_adjust(Option_, "sc22", -90000);
          return;
        }
    }
  if(_str_equal(Option_, "dec22"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc22");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec22");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec20", -90000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec23"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc23");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec23");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "sc24", 50000);
          return;
        }
      if(choice == 2)
        {
          _set_option_adjust(Option_, "sc28", -50000);
          return;
        }
    }
  if(_str_equal(Option_, "dec25"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc25");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec25");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "sc26", -75000);
          return;
        }
      if(choice == 2)
        {
          _set_option_adjust(Option_, "sc27", -90000);
          return;
        }
    }
  if(_str_equal(Option_, "dec26"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc26");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec26");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec25", -75000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec28"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc28");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec28");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec23", -75000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec29"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc29");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec29");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "sc30", -20000);
          return;
        }
      if(choice == 2)
        {
          _set_option_adjust(Option_, "sc31", 90000);
          return;
        }
    }
  if(_str_equal(Option_, "dec30"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc30");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec30");
          return;
        }
      if(choice == 1)
        {
          _set_option(Option_, "sc32");
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          startover = 1;
          return;
        }
      if(choice == 3)
        {
          _set_option(Option_, "end");
          return;
        }
    }
  if(_str_equal(Option_, "dec31"))
    {
      if(stepback == 1)
        {
          _set_option(Option_, "sc31");
          return;
        }
      if(choice == 0)
        {
          _set_option(Option_, "dec31");
          return;
        }
      if(choice == 1)
        {
          _set_option_adjust(Option_, "dec29", -20000);
          return;
        }
      if(choice == 2)
        {
          _set_option(Option_, "end");
          return;
        }
    }

  _set_option(Option_, "end");
}


int32
ShowCase(ScreenContext *TheScreen_,
         uint8         *Nscene_)
{
  int32 finish;
  int32 transition;

  if(!Nscene_)
    return -1;

  finish = 0;
  for(transition = 0; transition < SHOWCASE_MAX_TRANSITIONS; transition++)
    {
      showOption(Nscene_, &finish);
      stepback = 0;

      if(_str_equal(Nscene_, "sc13"))
        return 25;

      if(Nscene_[0] == 's')
        {
          finish = showpicture(TheScreen_, Nscene_);
          if(finish < 0)
            return -1;
        }
      if(Nscene_[0] == 'd')
        {
          finish = makedecision(TheScreen_, Nscene_);
          if(finish < 0)
            return -1;
        }
      if(_str_equal(Nscene_, "end"))
        return 100;
      if(Nscene_[0] != 's' && Nscene_[0] != 'd')
        return -1;
    }

  return -1;
}


int32
DEC13(void)
{
  uchar scene[10];
  Item fileItem;
  int32 result;

  if(!InitPicture(&gScreenContext))
    {
      return -1;
    }

  _copy_name(RootName, (const uchar *)"/cd-rom", 15);
  fileItem = OpenDiskFile("/cd-rom/tuntest/dec/dec13.data");
  if(fileItem >= 0)
    {
      CloseDiskFile(fileItem);
    }
  else
    {
      _copy_name(RootName, (const uchar *)"/remote", 15);
    }

  _copy_name(scene, (const uchar *)"dec13", 10);
  stepback = 0;
  result = ShowCase(&gScreenContext, scene);

  if(gBackPic)
    {
      FreeMem(gBackPic, _back_pic_size(&gScreenContext));
      gBackPic = 0;
    }
  if(startover)
    {
      startover = 0;
      result    = 50;
    }
  return result;
}
