/* ============================================================================
 * Reconstructed source: :MikeDS.c
 * Generated by armfd --reconstruct-sources from launchme.sym
 * ============================================================================ */

// MikeDS.c - scene sound/CEL effects.
#include "pdwt_scenes.h"

#include "3do_types.h"
#include "pdwt_app.h"
#include "pdwt_decision_audio.h"
#include "pdwt_input.h"
#include "pdwt_scene_control.h"
#include "pdwt_scene_data.h"
#include "pdwt_timing.h"

#include "celutils.h"
#include "item.h"
#include "kernel.h"
#include "task.h"

#include "stdio.h"
#include "string.h"

#define PDWT_AUDIONODE 4
#define PDWT_AUDIO_CUE_NODE 5
#define PDWT_MKNODEID(a, b) ((int32)(((a) << 8) | (b)))
#define PDWT_CUE_AT_END (-2)
#define PDWT_AF_TAG_AMPLITUDE (TAG_ITEM_LAST + 1)
#define PDWT_SOUNDFILE_BUFFER_SIZE 0xc000
#define PDWT_SOUNDFILE_AMPLITUDE 0x7fff
#define PDWT_STORY_BUFFER_COUNT 4
#define PDWT_STORY_BUFFER_SIZE 0x10000
#define PDWT_MEMTYPE_CEL 0x00040000
#define DEC00_TIMEOUT 2000
#define CONTROL_DOWN 0x80000000U
#define CONTROL_UP 0x40000000U
#define CONTROL_LEFT 0x10000000U
#define CONTROL_RIGHT 0x20000000U
#define CONTROL_A 0x08000000U
#define CONTROL_RIGHT_SHIFT 0x00400000U
#define CONTROL_LEFT_SHIFT 0x00200000U
#define CONTROL_B 0x04000000U
#define DECISION_SELECTED_X 0x00500000
#define DEC00_PIC1 "$boot/miketest/sc00/DEC001P.CEL"
#define DEC00_PIC2 "$boot/miketest/sc00/DEC001W.CEL"
#define DEC00_PIC3 "$boot/miketest/sc00/DEC002P.CEL"
#define DEC00_PIC4 "$boot/miketest/sc00/DEC002W.CEL"
#define DEC00_HELP "$boot/miketest/sc00/CONTROLHELP.CEL"
#define DEC00_SOUND1 "$boot/miketest/sc00/DEC001S.Aiff"
#define DEC00_SOUND2 "$boot/miketest/sc00/DEC002S.Aiff"
#ifndef DEC00_ENABLE_SOUND
  #define DEC00_ENABLE_SOUND 1
#endif
#define SC01_PATH_FORMAT "$boot/miketest/sc01/%s"
#define SC01_SOUND_FILE "$boot/miketest/sc01/DIA01.aiff"
#define SC02_PATH_FORMAT "$boot/miketest/sc02/%s"
#define SC02_SOUND_FILE "$boot/miketest/sc02/DIA02.aiff"
#define SC02_SHAKE_FIELDS (16 + (5 * 16) + 11)
#define SC03_PATH_FORMAT "$boot/miketest/sc03/%s"
#define SC03_SOUND_FILE "$boot/miketest/sc03/DIA03.aiff"
#define SC04_PATH_FORMAT "$boot/miketest/sc04/%s"
#define SC04A_PATH_FORMAT "$boot/miketest/sc04a/%s"
#define SC04_SOUND_FILE "$boot/miketest/sc04/DIA04.aiff"
#define SC04A_SOUND_FILE "$boot/miketest/sc04a/DIA04.aiff"
#define SC04_RATING_CEL "$boot/miketest/sc04/RATING.CEL"
#define SC04_RATING_START_FRAME 5
#define SC04_RATING_FIELDS 120
#define SC06_PATH_FORMAT "$boot/miketest/sc06/%s"
#define SC06_SOUND_FILE "$boot/miketest/sc06/DIA06.aiff"
#define SC07_PATH_FORMAT "$boot/miketest/sc07/%s"
#define SC07_SOUND_FILE "$boot/miketest/sc07/DIA07.aiff"
#define SC08_PATH_FORMAT "$boot/miketest/sc08/%s"
#define SC08_SOUND_FILE "$boot/miketest/sc08/DIA08.aiff"
#define SC09_PATH_FORMAT "$boot/miketest/sc09/%s"
#define SC09_SOUND_FILE "$boot/miketest/sc09/DIA09.aiff"
#define SC10_PATH_FORMAT "$boot/miketest/sc10/%s"
#define SC10_SOUND_FILE "$boot/miketest/sc10/DIA10.aiff"
#define DEC08_PIC1 "$boot/miketest/sc08a/DEC081P.CEL"
#define DEC08_PIC2 "$boot/miketest/sc08a/DEC082P.CEL"
#define DEC08_WIDE1 "$boot/miketest/sc08a/DEC081W.CEL"
#define DEC08_WIDE2 "$boot/miketest/sc08a/DEC082W.CEL"
#define DEC08_HELP "$boot/miketest/sc08a/CONTROLHELP.CEL"
#define DEC08_SOUND1 "$boot/miketest/sc08a/DEC081S.Aiff"
#define DEC08_SOUND2 "$boot/miketest/sc08a/DEC082S.Aiff"
#define DEC07_PIC1 "$boot/miketest/sc07a/DEC071P.CEL"
#define DEC07_PIC2 "$boot/miketest/sc07a/DEC072P.CEL"
#define DEC07_PIC3 "$boot/miketest/sc07a/DEC073P.CEL"
#define DEC07_WIDE1 "$boot/miketest/sc07a/DEC071W.CEL"
#define DEC07_WIDE2 "$boot/miketest/sc07a/DEC072W.CEL"
#define DEC07_WIDE3 "$boot/miketest/sc07a/DEC073W.CEL"
#define DEC07_HELP "$boot/miketest/sc07a/CONTROLHELP.CEL"
#define DEC07_SOUND1 "$boot/miketest/sc07a/DEC071S.Aiff"
#define DEC07_SOUND2 "$boot/miketest/sc07a/DEC072S.Aiff"
#define DEC07_SOUND3 "$boot/miketest/sc07a/DEC073S.Aiff"
#define SC11_PATH_FORMAT "$boot/miketest/sc11/%s"
#define SC11_SOUND_FILE "$boot/miketest/sc11/DIA11.aiff"
#define SC12_PATH_FORMAT "$boot/miketest/sc12/%s"
#define SC12_SOUND_FILE "$boot/miketest/sc12/DIA12.aiff"
#define SC13_PATH_FORMAT "$boot/miketest/sc13/%s"
#define SC13_SOUND_FILE "$boot/miketest/sc13/DIA13.aiff"
#define DEC12_PIC1 "$boot/miketest/sc12a/DEC121P.CEL"
#define DEC12_PIC2 "$boot/miketest/sc12a/DEC122P.CEL"
#define DEC12_WIDE1 "$boot/miketest/sc12a/DEC121W.CEL"
#define DEC12_WIDE2 "$boot/miketest/sc12a/DEC122W.CEL"
#define DEC12_HELP "$boot/miketest/sc12a/CONTROLHELP.CEL"
#define DEC12_SOUND1 "$boot/miketest/sc12a/DEC121S.Aiff"
#define DEC12_SOUND2 "$boot/miketest/sc12a/DEC122S.Aiff"

#define STANDARD_DECISION_MAX_CHOICES 3

typedef struct StandardDecisionConfig
{
  const char *normal_paths[STANDARD_DECISION_MAX_CHOICES];
  const char *selected_paths[STANDARD_DECISION_MAX_CHOICES];
  const char *sound_paths[STANDARD_DECISION_MAX_CHOICES];
  const char *help_path;
  int32 choice_count;
  int32 cel_height;
  int32 exit_result;
} StandardDecisionConfig;

typedef struct StandardDecisionState
{
  DecisionAudio audio;
  CCB          *normal[STANDARD_DECISION_MAX_CHOICES];
  CCB          *selected[STANDARD_DECISION_MAX_CHOICES];
  CCB          *help;
  Item vram_io_req;
  Item vbl_io_req;
  GrafCon gcon;
  uint8 score_text[28];
  int32 event_open;
} StandardDecisionState;

static const StandardDecisionConfig g_dec07_config =
{
  {
    DEC07_PIC1,
    DEC07_PIC2,
    DEC07_PIC3
  },
  {
    DEC07_WIDE1,
    DEC07_WIDE2,
    DEC07_WIDE3
  },
  {
    DEC07_SOUND1,
    DEC07_SOUND2,
    DEC07_SOUND3
  },
  DEC07_HELP,
  3,
  60,
  5
};

static const StandardDecisionConfig g_dec12_config =
{
  {
    DEC12_PIC1,
    DEC12_PIC2,
    NULL
  },
  {
    DEC12_WIDE1,
    DEC12_WIDE2,
    NULL
  },
  {
    DEC12_SOUND1,
    DEC12_SOUND2,
    NULL
  },
  DEC12_HELP,
  2,
  100,
  3
};

static const StandardDecisionConfig g_dec08_config =
{
  {
    DEC08_PIC1,
    DEC08_PIC2,
    NULL
  },
  {
    DEC08_WIDE1,
    DEC08_WIDE2,
    NULL
  },
  {
    DEC08_SOUND1,
    DEC08_SOUND2,
    NULL
  },
  DEC08_HELP,
  2,
  100,
  3
};

static
int32
_run_standard_decision(const StandardDecisionConfig *config_);

static
int32
_init_standard_decision(const StandardDecisionConfig *config_,
                        StandardDecisionState        *state_);

static
void
_set_standard_decision_flags(const StandardDecisionConfig *config_,
                             int32                         choice_);

static
void
_draw_standard_decision(const StandardDecisionConfig *config_,
                        StandardDecisionState        *state_,
                        int32                         help_visible_);

static
int32
_cleanup_standard_decision(const StandardDecisionConfig *config_,
                           StandardDecisionState        *state_);


static
void
_set_dec00_cel_pos(CCB *cel_);


static
void
_setup_decision_cel(CCB  *cel_,
                    int32 width_,
                    int32 height_,
                    Coord xpos_,
                    Coord ypos_);


static
void
_set_dec00_render_flags(int32 choice_);


static
void
_set_dec07_render_flags(int32 choice_);


static
void
_set_dec12_render_flags(int32 choice_);


static
void
_draw_dec00_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *eccb1_,
                  CCB     *eccb1w_,
                  CCB     *eccb2_,
                  CCB     *eccb2w_,
                  CCB     *controlhelp_,
                  int32    helpVisible_);


static
void
_draw_dec07_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *normal1_,
                  CCB     *normal2_,
                  CCB     *normal3_,
                  CCB     *selected1_,
                  CCB     *selected2_,
                  CCB     *selected3_,
                  CCB     *controlhelp_,
                  int32    helpVisible_);


static
void
_draw_dec12_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *normal1_,
                  CCB     *normal2_,
                  CCB     *selected1_,
                  CCB     *selected2_,
                  CCB     *controlhelp_,
                  int32    helpVisible_);


static
CCB *
_load_scene_cel(char         *pathFormat_,
                SceneCelInfo *info_,
                uint8        *path_);


static
void
_prepare_scene_cel(CCB *cel_);


static
uint32
_scene_table_fields(const SceneCelInfo *table_,
                    int32               count_);


static
int32
_wait_for_scene_fields(Item  vblIOReq_,
                       int32 fields_);


static
int32
_wait_for_scene_clock(PDWTSceneClock *clock_,
                      Item            vblIOReq_,
                      int32           fields_);


static
int32
_wait_for_scene_audio(DecisionAudio *audio_,
                      Item           vblIOReq_);


static
int32
_wait_for_uncalibrated_scene_audio(const PDWTSceneClock *clock_,
                                   DecisionAudio        *audio_,
                                   Item                  vblIOReq_);


static
int32
_wait_for_calibrated_scene_end(PDWTSceneClock *clock_,
                               Item            vblIOReq_);


static
int32
_stop_scene_audio(DecisionAudio *audio_,
                  int32          result_);


static
int32
_finish_scene_result(int32 result_);


static
int32
_draw_scene_cel(Item  vramIOReq_,
                Item  vblIOReq_,
                CCB  *cel_,
                int32 fields_);


static
int32
_draw_scene_table_frame(char           *pathFormat_,
                        SceneCelInfo   *info_,
                        Item            vramIOReq_,
                        Item            vblIOReq_,
                        uint8          *path_,
                        PDWTSceneClock *clock_);


static
void
_flip_screen(void);


static
void
_clear_current_screen(Item vramIOReq_);


static
void
_show_current_screen(void);


static
void
_restore_next_screen(Item vramIOReq_);


static
void
_draw_transition_frame(Item   vramIOReq_,
                       CCB   *cel_,
                       Point *quad_);


static
void
_init_quad(Point *quad_,
           Coord  x0_,
           Coord  y0_,
           Coord  x1_,
           Coord  y1_,
           Coord  x2_,
           Coord  y2_,
           Coord  x3_,
           Coord  y3_);


static
void
_set_dec00_cel_pos(CCB *cel_)
{
  cel_->ccb_Width  = 80;
  cel_->ccb_Height = 100;
}


static
void
_setup_decision_cel(CCB  *cel_,
                    int32 width_,
                    int32 height_,
                    Coord xpos_,
                    Coord ypos_)
{
  cel_->ccb_Width  = width_;
  cel_->ccb_Height = height_;
  cel_->ccb_XPos   = xpos_;
  cel_->ccb_YPos   = ypos_;
}


static
void
_set_dec00_render_flags(int32 choice_)
{
  if(choice_ == 1)
    {
      Cel5->ccb_Flags = (Cel5->ccb_Flags & ~0x180) | 0x100;
      Cel4->ccb_Flags = (Cel4->ccb_Flags & ~0x100) | 0x180;
    }
  else
    {
      Cel5->ccb_Flags = (Cel5->ccb_Flags & ~0x100) | 0x180;
      Cel4->ccb_Flags = (Cel4->ccb_Flags & ~0x180) | 0x100;
    }
}


static
void
_set_dec07_render_flags(int32 choice_)
{
  if(choice_ == 1)
    {
      Cel3->ccb_Flags = (Cel3->ccb_Flags & ~0x180) | 0x100;
      Cel2->ccb_Flags = (Cel2->ccb_Flags & ~0x180) | 0x100;
      Cel1->ccb_Flags = (Cel1->ccb_Flags & ~0x100) | 0x180;
    }
  else if(choice_ == 2)
    {
      Cel3->ccb_Flags = (Cel3->ccb_Flags & ~0x180) | 0x100;
      Cel2->ccb_Flags = (Cel2->ccb_Flags & ~0x100) | 0x180;
      Cel1->ccb_Flags = (Cel1->ccb_Flags & ~0x180) | 0x100;
    }
  else
    {
      Cel3->ccb_Flags = (Cel3->ccb_Flags & ~0x100) | 0x180;
      Cel2->ccb_Flags = (Cel2->ccb_Flags & ~0x180) | 0x100;
      Cel1->ccb_Flags = (Cel1->ccb_Flags & ~0x180) | 0x100;
    }
}


static
void
_set_dec12_render_flags(int32 choice_)
{
  if(choice_ == 1)
    {
      Cel5->ccb_Flags = (Cel5->ccb_Flags & ~0x180) | 0x100;
      Cel4->ccb_Flags = (Cel4->ccb_Flags & ~0x100) | 0x180;
    }
  else
    {
      Cel5->ccb_Flags = (Cel5->ccb_Flags & ~0x100) | 0x180;
      Cel4->ccb_Flags = (Cel4->ccb_Flags & ~0x180) | 0x100;
    }
}


static
void
_draw_dec00_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *eccb1_,
                  CCB     *eccb1w_,
                  CCB     *eccb2_,
                  CCB     *eccb2w_,
                  CCB     *controlhelp_,
                  int32    helpVisible_)
{
  Item screenBitmapItem;
  Bitmap      *screenBitmap;

  gcon_->gc_PenX = 20;
  gcon_->gc_PenY = 216;
  if(vramIOReq_ <= 0)
    {
      return;
    }

  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;

  screenBitmapItem = gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen];
  screenBitmap     = gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen];
  if(screenBitmap == 0)
    {
      return;
    }


  (void)DrawCels(itemRenderBitmap4, eccb1_);
  (void)DrawCels(itemRenderBitmap5, eccb2_);
  (void)DrawCels(itemRenderBitmap4, eccb1w_);
  (void)DrawCels(itemRenderBitmap5, eccb2w_);

  (void)SetVRAMPages(vramIOReq_, screenBitmap->bm_Buffer, 0, gScreenContext.sc_nFrameBufferPages,
                     -1);

  (void)DrawCels(screenBitmapItem, Cel4);
  (void)DrawCels(screenBitmapItem, Cel5);
  if(helpVisible_)
    {
      (void)DrawCels(screenBitmapItem, controlhelp_);
    }
  (void)DrawText8(gcon_, screenBitmapItem, scoreText_);

  (void)DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
}


static
void
_draw_dec07_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *normal1_,
                  CCB     *normal2_,
                  CCB     *normal3_,
                  CCB     *selected1_,
                  CCB     *selected2_,
                  CCB     *selected3_,
                  CCB     *controlhelp_,
                  int32    helpVisible_)
{
  Item screenBitmapItem;
  Bitmap      *screenBitmap;

  gcon_->gc_PenX = 20;
  gcon_->gc_PenY = 216;
  if(vramIOReq_ <= 0)
    {
      return;
    }

  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;

  screenBitmapItem = gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen];
  screenBitmap     = gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen];
  if(screenBitmap == 0)
    {
      return;
    }

  (void)DrawCels(itemRenderBitmap1, normal1_);
  (void)DrawCels(itemRenderBitmap2, normal2_);
  (void)DrawCels(itemRenderBitmap3, normal3_);
  (void)DrawCels(itemRenderBitmap1, selected1_);
  (void)DrawCels(itemRenderBitmap2, selected2_);
  (void)DrawCels(itemRenderBitmap3, selected3_);

  (void)SetVRAMPages(vramIOReq_, screenBitmap->bm_Buffer, 0, gScreenContext.sc_nFrameBufferPages,
                     -1);

  (void)DrawCels(screenBitmapItem, Cel3);
  (void)DrawCels(screenBitmapItem, Cel2);
  (void)DrawCels(screenBitmapItem, Cel1);

  (void)DrawText8(gcon_, screenBitmapItem, scoreText_);
  if(helpVisible_)
    {
      (void)DrawCels(screenBitmapItem, controlhelp_);
    }

  (void)DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
}


static
void
_draw_dec12_scene(Item     vramIOReq_,
                  GrafCon *gcon_,
                  uint8   *scoreText_,
                  CCB     *normal1_,
                  CCB     *normal2_,
                  CCB     *selected1_,
                  CCB     *selected2_,
                  CCB     *controlhelp_,
                  int32    helpVisible_)
{
  Item screenBitmapItem;
  Bitmap      *screenBitmap;

  gcon_->gc_PenX = 20;
  gcon_->gc_PenY = 216;
  if(vramIOReq_ <= 0)
    {
      return;
    }

  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;

  screenBitmapItem = gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen];
  screenBitmap     = gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen];
  if(screenBitmap == 0)
    {
      return;
    }

  (void)DrawCels(itemRenderBitmap4, normal1_);
  (void)DrawCels(itemRenderBitmap5, normal2_);
  (void)DrawCels(itemRenderBitmap4, selected1_);
  (void)DrawCels(itemRenderBitmap5, selected2_);

  (void)SetVRAMPages(vramIOReq_, screenBitmap->bm_Buffer, 0, gScreenContext.sc_nFrameBufferPages,
                     -1);

  (void)DrawCels(screenBitmapItem, Cel4);
  (void)DrawCels(screenBitmapItem, Cel5);

  (void)DrawText8(gcon_, screenBitmapItem, scoreText_);
  if(helpVisible_)
    {
      (void)DrawCels(screenBitmapItem, controlhelp_);
    }

  (void)DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
}


static
int32
_run_standard_decision(const StandardDecisionConfig *config_)
{
  StandardDecisionState state;
  int32 audio_result;
  int32 buttons;
  int32 choice;
  int32 cleanup_result;
  int32 help_visible;
  int32 result;
  int32 running;
  int32 selection_changed;
  int32 voiced_choice;

  choice = 1;
  result = _init_standard_decision(config_, &state);
  if(result != 0)
    {
      goto cleanup;
    }

  help_visible      = 0;
  running           = 1;
  voiced_choice     = 0;
  selection_changed = 0;
  _set_standard_decision_flags(config_, choice);

  while(running)
    {
      _draw_standard_decision(config_, &state, help_visible);

      selection_changed = 0;
      result            = WaitVBL(state.vbl_io_req, 1);
      if(result < 0)
        {
          break;
        }
      audio_result = DecisionAudioService(&state.audio);
      if(audio_result < 0)
        {
          result = audio_result;
          break;
        }

      buttons      = GetJoypad();
      help_visible = ((controlPadPrevious.cped_ButtonBits & CONTROL_LEFT_SHIFT) != 0);
      if(controlPadLastError < 0)
        {
          result = controlPadLastError;
          break;
        }
      if(buttons == (int32)CONTROL_RIGHT_SHIFT)
        {
          result  = config_->exit_result;
          running = 0;
        }
      else if(buttons == (int32)CONTROL_DOWN)
        {
          choice++;
          if(choice > config_->choice_count)
            {
              choice = 1;
            }
          _set_standard_decision_flags(config_, choice);
          selection_changed = 1;
        }
      else if(!help_visible && buttons == (int32)CONTROL_A)
        {
          running = 0;
        }
      else if(!help_visible && buttons == (int32)CONTROL_UP)
        {
          choice--;
          if(choice < 1)
            {
              choice = config_->choice_count;
            }
          _set_standard_decision_flags(config_, choice);
          selection_changed = 1;
        }

      if(selection_changed && running)
        {
          _draw_standard_decision(config_, &state, help_visible);
        }

      if(running && choice != voiced_choice)
        {
          audio_result = DecisionAudioStart(
            &state.audio,
            (uint8 *)config_->sound_paths[choice - 1],
            PDWT_SOUNDFILE_BUFFER_SIZE,
            PDWT_SOUNDFILE_AMPLITUDE);
          if(audio_result < 0)
            {
              result = audio_result;
              break;
            }
          voiced_choice = choice;
        }
    }

cleanup:
  _restore_next_screen(state.vram_io_req);
  cleanup_result = _cleanup_standard_decision(config_, &state);
  if(cleanup_result < 0 && result >= 0)
    {
      result = cleanup_result;
    }
  if(result != 0)
    {
      return result;
    }
  return choice;
}


static
int32
_init_standard_decision(const StandardDecisionConfig *config_,
                        StandardDecisionState        *state_)
{
  int32 i;
  int32 result;

  memset(state_, 0, sizeof(*state_));
  DecisionAudioInit(&state_->audio);

  result = InitEventUtility(1, 0, 1);
  if(result != 0)
    {
      return result < 0 ? result : -1;
    }
  state_->event_open = 1;

  state_->vram_io_req = GetVRAMIOReq();
  if(state_->vram_io_req < 0)
    {
      return state_->vram_io_req;
    }
  state_->vbl_io_req = GetVBLIOReq();
  if(state_->vbl_io_req < 0)
    {
      return state_->vbl_io_req;
    }

  for(i = 0; i < config_->choice_count; i++)
    {
      state_->normal[i] = LoadCel((char *)config_->normal_paths[i], PDWT_MEMTYPE_CEL);
      if(state_->normal[i] == NULL)
        {
          return -1;
        }
      state_->selected[i] = LoadCel((char *)config_->selected_paths[i], PDWT_MEMTYPE_CEL);
      if(state_->selected[i] == NULL)
        {
          return -1;
        }

      _setup_decision_cel(state_->normal[i], 80, config_->cel_height, 0, 0);
      _setup_decision_cel(
        state_->selected[i],
        80,
        config_->cel_height,
        DECISION_SELECTED_X,
        0);
    }

  state_->help = LoadCel((char *)config_->help_path, PDWT_MEMTYPE_CEL);
  if(state_->help == NULL)
    {
      return -1;
    }

  sprintf((char *)state_->score_text, "SCORES:%d", point);
  return 0;
}


static
void
_set_standard_decision_flags(const StandardDecisionConfig *config_,
                             int32                         choice_)
{
  if(config_->choice_count == 3)
    {
      _set_dec07_render_flags(choice_);
    }
  else
    {
      _set_dec12_render_flags(choice_);
    }
}


static
void
_draw_standard_decision(const StandardDecisionConfig *config_,
                        StandardDecisionState        *state_,
                        int32                         help_visible_)
{
  if(config_->choice_count == 3)
    {
      _draw_dec07_scene(
        state_->vram_io_req,
        &state_->gcon,
        state_->score_text,
        state_->normal[0],
        state_->normal[1],
        state_->normal[2],
        state_->selected[0],
        state_->selected[1],
        state_->selected[2],
        state_->help,
        help_visible_);
    }
  else
    {
      _draw_dec12_scene(
        state_->vram_io_req,
        &state_->gcon,
        state_->score_text,
        state_->normal[0],
        state_->normal[1],
        state_->selected[0],
        state_->selected[1],
        state_->help,
        help_visible_);
    }
}


static
int32
_cleanup_standard_decision(const StandardDecisionConfig *config_,
                           StandardDecisionState        *state_)
{
  int32 cleanup_result;
  int32 i;
  int32 result;

  result = DecisionAudioStop(&state_->audio);
  if(state_->event_open)
    {
      cleanup_result = KillEventUtility();
      if(cleanup_result < 0 && result >= 0)
        {
          result = cleanup_result;
        }
    }

  for(i = 0; i < config_->choice_count; i++)
    {
      if(state_->normal[i] != NULL)
        {
          UnloadCel(state_->normal[i]);
        }
      if(state_->selected[i] != NULL)
        {
          UnloadCel(state_->selected[i]);
        }
    }
  if(state_->help != NULL)
    {
      UnloadCel(state_->help);
    }

  if(state_->vbl_io_req > 0)
    {
      cleanup_result = DeleteItem(state_->vbl_io_req);
      if(cleanup_result < 0 && result >= 0)
        {
          result = cleanup_result;
        }
    }
  if(state_->vram_io_req > 0)
    {
      cleanup_result = DeleteItem(state_->vram_io_req);
      if(cleanup_result < 0 && result >= 0)
        {
          result = cleanup_result;
        }
    }

  return result;
}


static
CCB *
_load_scene_cel(char         *pathFormat_,
                SceneCelInfo *info_,
                uint8        *path_)
{
  CCB *cel;

  sprintf((char *)path_, pathFormat_, info_->CelFileName);
  cel = LoadCel((char *)path_, PDWT_MEMTYPE_CEL);
  return cel;
}


static
void
_prepare_scene_cel(CCB *cel_)
{
  cel_->ccb_Flags |= 0x40000000;
  cel_->ccb_XPos = ((320 - cel_->ccb_Width) / 2) << 16;
  cel_->ccb_YPos = 0;
}


static
uint32
_scene_table_fields(const SceneCelInfo *table_,
                    int32               count_)
{
  uint32 fields;
  int32 frame;

  fields = 0;
  for(frame = 0; frame < count_; frame++)
    {
      fields += (uint32)table_[frame].CelLength;
    }
  return fields;
}


static
int32
_wait_for_scene_fields(Item  vblIOReq_,
                       int32 fields_)
{
  int32 result;

  result = PDWTSceneControlWaitFields(vblIOReq_, fields_);
  if(result == PDWT_INPUT_STOP)
    {
      return 3;
    }
  return result;
}


static
int32
_wait_for_scene_clock(PDWTSceneClock *clock_,
                      Item            vblIOReq_,
                      int32           fields_)
{
  int32 result;

  result = PDWTSceneControlWaitClock(clock_, vblIOReq_, fields_);
  if(result == PDWT_INPUT_STOP)
    {
      return 3;
    }
  return result;
}


static
int32
_wait_for_scene_audio(DecisionAudio *audio_,
                      Item           vblIOReq_)
{
  return PDWTSceneControlWaitAudio(audio_, vblIOReq_);
}


static
int32
_wait_for_uncalibrated_scene_audio(const PDWTSceneClock *clock_,
                                   DecisionAudio        *audio_,
                                   Item                  vblIOReq_)
{
  if(PDWTSceneClockIsCalibrated(clock_))
    {
      return 0;
    }
  return _wait_for_scene_audio(audio_, vblIOReq_);
}


static
int32
_wait_for_calibrated_scene_end(PDWTSceneClock *clock_,
                               Item            vblIOReq_)
{
  int32 result;

  if(!PDWTSceneClockIsCalibrated(clock_))
    {
      return 0;
    }
  result = PDWTSceneControlWaitClockEnd(clock_, vblIOReq_);
  if(result == PDWT_INPUT_STOP)
    {
      return 3;
    }
  return result;
}


static
int32
_stop_scene_audio(DecisionAudio *audio_,
                  int32          result_)
{
  int32 stopResult;

  stopResult = DecisionAudioStop(audio_);
  if(stopResult < 0 && result_ >= 0)
    {
      return stopResult;
    }
  return result_;
}


static
int32
_finish_scene_result(int32 result_)
{
  if(result_ == PDWT_SCENE_CONTROL_SKIP)
    {
      return 1;
    }
  if(result_ != 0)
    {
      return result_ == 1 ? -1 : result_;
    }
  return 1;
}


static
int32
_draw_scene_cel(Item  vramIOReq_,
                Item  vblIOReq_,
                CCB  *cel_,
                int32 fields_)
{
  int32 result;

  if(vramIOReq_ <= 0 || vblIOReq_ <= 0 || cel_ == NULL)
    {
      return -1;
    }

  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;
  result = SetVRAMPages(
    vramIOReq_,
    gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen]->bm_Buffer,
    0,
    gScreenContext.sc_nFrameBufferPages,
    -1);
  if(result < 0)
    {
      return result;
    }
  result = DrawCels(gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen], cel_);
  if(result < 0)
    {
      return result;
    }
  result = DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
  if(result < 0)
    {
      return result;
    }
  PDWTSceneControlPresent(gScreenContext.sc_curScreen);
  return _wait_for_scene_fields(vblIOReq_, fields_);
}


static
int32
_draw_scene_table_frame(char           *pathFormat_,
                        SceneCelInfo   *info_,
                        Item            vramIOReq_,
                        Item            vblIOReq_,
                        uint8          *path_,
                        PDWTSceneClock *clock_)
{
  CCB  *cel;
  int32 result;

  if(vramIOReq_ <= 0 || vblIOReq_ <= 0)
    {
      return -1;
    }

  cel = _load_scene_cel(pathFormat_, info_, path_);
  if(cel == NULL)
    {
      return -1;
    }
  _prepare_scene_cel(cel);
  result = _draw_scene_cel(vramIOReq_, vblIOReq_, cel, 0);
  UnloadCel(cel);
  if(result == 0)
    {
      result = _wait_for_scene_clock(clock_, vblIOReq_, info_->CelLength);
    }
  return result;
}


static
void
_flip_screen(void)
{
  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;
}


static
void
_clear_current_screen(Item vramIOReq_)
{
  Bitmap *bitmap;

  if(vramIOReq_ <= 0)
    {
      return;
    }

  bitmap = gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen];
  if(bitmap == NULL)
    {
      return;
    }

  SetVRAMPages(vramIOReq_, bitmap->bm_Buffer, 0, gScreenContext.sc_nFrameBufferPages, -1);
}


static
void
_show_current_screen(void)
{
  DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
  PDWTSceneControlPresent(gScreenContext.sc_curScreen);
}


static
void
_restore_next_screen(Item vramIOReq_)
{
  Bitmap *bitmap;

  if(vramIOReq_ <= 0)
    {
      return;
    }

  gScreenContext.sc_curScreen = 1 - gScreenContext.sc_curScreen;
  bitmap                      = gScreenContext.sc_Bitmaps[gScreenContext.sc_curScreen];
  if(bitmap != NULL)
    {
      SetVRAMPages(vramIOReq_, bitmap->bm_Buffer, 0, gScreenContext.sc_nFrameBufferPages, -1);
    }
  DisplayScreen(gScreenContext.sc_Screens[gScreenContext.sc_curScreen], 0);
  PDWTSceneControlPresent(gScreenContext.sc_curScreen);
}


static
void
_draw_transition_frame(Item   vramIOReq_,
                       CCB   *cel_,
                       Point *quad_)
{
  if(vramIOReq_ <= 0 || cel_ == NULL || quad_ == NULL)
    {
      return;
    }

  _flip_screen();
  MapCel(cel_, quad_);
  _clear_current_screen(vramIOReq_);
  DrawCels(gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen], cel_);
  _show_current_screen();
}


static
void
_init_quad(Point *quad_,
           Coord  x0_,
           Coord  y0_,
           Coord  x1_,
           Coord  y1_,
           Coord  x2_,
           Coord  y2_,
           Coord  x3_,
           Coord  y3_)
{
  quad_[0].pt_X = x0_;
  quad_[0].pt_Y = y0_;
  quad_[1].pt_X = x1_;
  quad_[1].pt_Y = y1_;
  quad_[2].pt_X = x2_;
  quad_[2].pt_Y = y2_;
  quad_[3].pt_X = x3_;
  quad_[3].pt_Y = y3_;
}


int32
FUNeffectout(CCB *cel_)
{
  Item vramIOReq;
  Point quad[4];
  int32 result;

  result    = 0;
  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    {
      return vramIOReq;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  _show_current_screen();
  result = PDWTSceneControlPoll();
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  _init_quad(quad, 120, 120, 200, 120, 200, 120, 120, 120);
  while(quad[0].pt_X > 0)
    {
      quad[0].pt_X--;
      quad[0].pt_Y--;
      quad[1].pt_X++;
      quad[1].pt_Y--;
      quad[2].pt_X++;
      quad[2].pt_Y++;
      quad[3].pt_X--;
      quad[3].pt_Y++;
      _draw_transition_frame(vramIOReq, cel_, quad);
      result = PDWTSceneControlPoll();
      if(result != PDWT_SCENE_CONTROL_CONTINUE)
        {
          goto cleanup;
        }
    }

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  return result;
}


int32
FUNSC02effectout(CCB *cel_)
{
  Item vramIOReq;
  Point quad[4];
  int32 result;

  result    = 0;
  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    {
      return vramIOReq;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  _show_current_screen();
  result = PDWTSceneControlPoll();
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  _init_quad(quad, 120, 120, 200, 120, 200, 120, 120, 120);
  while(quad[0].pt_X > 0)
    {
      quad[0].pt_X -= 2;
      quad[0].pt_Y -= 2;
      quad[1].pt_X += 2;
      quad[1].pt_Y -= 2;
      quad[2].pt_X += 2;
      quad[2].pt_Y += 2;
      quad[3].pt_X -= 2;
      quad[3].pt_Y += 2;
      _draw_transition_frame(vramIOReq, cel_, quad);
      result = PDWTSceneControlPoll();
      if(result != PDWT_SCENE_CONTROL_CONTINUE)
        {
          goto cleanup;
        }
    }

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  return result;
}


int32
FUNeffectouth(CCB *cel_)
{
  Item vramIOReq;
  Point quad[4];
  int32 result;

  result    = 0;
  vramIOReq = GetVRAMIOReq();
  if(vramIOReq < 0)
    {
      return vramIOReq;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  _show_current_screen();
  result = PDWTSceneControlPoll();
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  _init_quad(quad, 140, 120, 180, 120, 180, 120, 140, 120);
  while(quad[0].pt_X > 80)
    {
      quad[0].pt_X--;
      quad[0].pt_Y -= 2;
      quad[1].pt_X++;
      quad[1].pt_Y -= 2;
      quad[2].pt_X++;
      quad[2].pt_Y += 2;
      quad[3].pt_X--;
      quad[3].pt_Y += 2;
      _draw_transition_frame(vramIOReq, cel_, quad);
      result = PDWTSceneControlPoll();
      if(result != PDWT_SCENE_CONTROL_CONTINUE)
        {
          goto cleanup;
        }
    }

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  return result;
}


int32
FUNeffectin(CCB *cel_)
{
  Item vramIOReq;
  Item vblIOReq;
  Point quad[4];
  int32 result;

  result    = 0;
  vramIOReq = GetVRAMIOReq();
  vblIOReq  = GetVBLIOReq();
  if(vramIOReq < 0 || vblIOReq < 0)
    {
      result = -1;
      goto cleanup;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  _show_current_screen();

  _init_quad(quad, 0, 0, 320, 0, 320, 240, 0, 240);
  while(quad[0].pt_X < 120)
    {
      quad[0].pt_X++;
      quad[0].pt_Y++;
      quad[1].pt_X--;
      quad[1].pt_Y++;
      quad[2].pt_X--;
      quad[2].pt_Y--;
      quad[3].pt_X++;
      quad[3].pt_Y--;
      _draw_transition_frame(vramIOReq, cel_, quad);
      result = _wait_for_scene_fields(vblIOReq, 1);
      if(result != 0)
        {
          goto cleanup;
        }
    }

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


int32
FUNeffectinh(CCB *cel_)
{
  Item vramIOReq;
  Item vblIOReq;
  Point quad[4];
  int32 result;

  result    = 0;
  vramIOReq = GetVRAMIOReq();
  vblIOReq  = GetVBLIOReq();
  if(vramIOReq < 0 || vblIOReq < 0)
    {
      result = -1;
      goto cleanup;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  _show_current_screen();

  _init_quad(quad, 80, 0, 240, 0, 240, 240, 80, 240);
  while(quad[0].pt_X < 140)
    {
      quad[0].pt_X++;
      quad[0].pt_Y += 2;
      quad[1].pt_X--;
      quad[1].pt_Y += 2;
      quad[2].pt_X--;
      quad[2].pt_Y -= 2;
      quad[3].pt_X++;
      quad[3].pt_Y -= 2;
      _draw_transition_frame(vramIOReq, cel_, quad);
      result = _wait_for_scene_fields(vblIOReq, 1);
      if(result != 0)
        {
          goto cleanup;
        }
    }

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


int32
shakeeffect(CCB *cel_)
{
  Item vramIOReq;
  Item vblIOReq;
  Point quad[4];
  int32 outer;
  int32 inner;
  int32 result;

  outer     = 0;
  inner     = 0;
  result    = 0;
  vramIOReq = GetVRAMIOReq();
  vblIOReq  = GetVBLIOReq();
  if(vramIOReq < 0 || vblIOReq < 0)
    {
      result = -1;
      goto cleanup;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  result = _wait_for_scene_fields(vblIOReq, 16);
  if(result != 0)
    {
      goto cleanup;
    }

  _init_quad(quad, 0, 0, 320, 0, 320, 240, 0, 240);
  while(outer < 5)
    {
      while(inner < 8)
        {
          quad[0].pt_X -= 35;
          quad[1].pt_X += 35;
          quad[2].pt_X += 35;
          quad[3].pt_X -= 35;
          quad[2].pt_Y += 70;
          quad[3].pt_Y += 70;
          _draw_transition_frame(vramIOReq, cel_, quad);
          result = _wait_for_scene_fields(vblIOReq, 1);
          if(result != 0)
            {
              goto cleanup;
            }
          inner++;
        }
      while(inner < 16)
        {
          quad[0].pt_X += 35;
          quad[1].pt_X -= 35;
          quad[2].pt_X -= 35;
          quad[3].pt_X += 35;
          quad[2].pt_Y -= 70;
          quad[3].pt_Y -= 70;
          _draw_transition_frame(vramIOReq, cel_, quad);
          result = _wait_for_scene_fields(vblIOReq, 1);
          if(result != 0)
            {
              goto cleanup;
            }
          inner++;
        }
      inner = 0;
      outer++;
    }

  _flip_screen();
  _clear_current_screen(vramIOReq);
  DrawCels(gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen], cel_);
  _show_current_screen();
  result = _wait_for_scene_fields(vblIOReq, 11);

cleanup:
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  return result;
}


int32
PlaySoundFile(SoundFilePlayer *sfp_,
              uint8           *FileName_)
{
  int32 cleanupResult;
  int32 err;
  int32 signalIn;
  int32 signalNeeded;
  int32 loaded;
  int32 started;

  err          = 0;
  signalIn     = 0;
  signalNeeded = 0;
  loaded       = 0;
  started      = 0;

  if(sfp_ == NULL)
    {
      return -1;
    }

  err = LoadSoundFile(sfp_, (char *)FileName_);
  if(err < 0)
    {
      return err;
    }
  loaded = 1;

  err = StartSoundFile(sfp_, 0x7fff);
  if(err < 0)
    {
      goto cleanup;
    }
  started = 1;

  do
    {
      err = ServiceSoundFile(sfp_, signalIn, &signalNeeded);
      if(err < 0)
        {
          goto cleanup;
        }
      if(signalNeeded != 0)
        {
          signalIn = WaitSignal((uint32)signalNeeded);
        }
    } while(signalNeeded != 0);

cleanup:
  if(started)
    {
      cleanupResult = StopSoundFile(sfp_);
      if(cleanupResult < 0)
        {
          return err < 0 ? err : cleanupResult;
        }
    }
  if(loaded)
    {
      cleanupResult = UnloadSoundFile(sfp_);
      if(cleanupResult < 0)
        {
          return err < 0 ? err : cleanupResult;
        }
    }

  return err < 0 ? err : 0;
}


int32
DEC00(void)
{
  DecisionAudio decisionAudio;
  Item vramIOReq;
  Item vblIOReq;
  GrafCon gcon;
  uint8 scoreText[28];
  const uint8 *sound_name;
  CCB          *eccb1;
  CCB          *eccb1w;
  CCB          *eccb2;
  CCB          *eccb2w;
  CCB          *controlhelp;
  int32 choice;
  int32 voicedChoice;
  int32 running;
  int32 canPlaySound;
  int32 eventOpen;
  int32 audioEnabled;
  int32 renderReady;
  int32 cel1Loaded;
  int32 cel2Loaded;
  int32 cel3Loaded;
  int32 cel4Loaded;
  int32 cel5Loaded;
  int32 helpVisible;
  int32 ticks;
  int32 buttons;
  int32 result;
  int32 eventErr;
  int32 audioResult;

  DecisionAudioInit(&decisionAudio);
  vramIOReq        = 0;
  vblIOReq         = 0;
  eccb1            = 0;
  eccb1w           = 0;
  eccb2            = 0;
  eccb2w           = 0;
  controlhelp      = 0;
  choice           = 1;
  voicedChoice     = 0;
  running          = 1;
  canPlaySound     = 1;
  eventOpen        = 0;
  audioEnabled     = DEC00_ENABLE_SOUND;
  renderReady      = 1;
  cel1Loaded       = 1;
  cel2Loaded       = 1;
  cel3Loaded       = 1;
  cel4Loaded       = 1;
  cel5Loaded       = 1;
  helpVisible      = 0;
  ticks            = 0;
  result           = 1;

  eventErr = InitEventUtility(1, 0, 1);
  if(eventErr != 0)
    {
      canPlaySound = 0;
      eventOpen    = 0;
    }
  else
    {
      eventOpen = 1;
    }

  vramIOReq = GetVRAMIOReq();
  vblIOReq = GetVBLIOReq();
  if(vramIOReq < 0 || vblIOReq < 0)
    {
      result      = -1;
      renderReady = 0;
      running     = 0;
    }

  eccb1 = LoadCel(DEC00_PIC1, PDWT_MEMTYPE_CEL);
  if(eccb1 == 0)
    {
      cel1Loaded = 0;
    }
  eccb1w = LoadCel(DEC00_PIC2, PDWT_MEMTYPE_CEL);
  if(eccb1w == 0)
    {
      cel2Loaded = 0;
    }
  eccb2 = LoadCel(DEC00_PIC3, PDWT_MEMTYPE_CEL);
  if(eccb2 == 0)
    {
      cel3Loaded = 0;
    }
  eccb2w = LoadCel(DEC00_PIC4, PDWT_MEMTYPE_CEL);
  if(eccb2w == 0)
    {
      cel4Loaded = 0;
    }
  controlhelp = LoadCel(DEC00_HELP, PDWT_MEMTYPE_CEL);
  if(controlhelp == 0)
    {
      cel5Loaded = 0;
    }

  renderReady = (Cel4 != 0 && Cel5 != 0);
  if(!cel1Loaded || !cel2Loaded || !cel3Loaded || !cel4Loaded || !cel5Loaded || !renderReady ||
     !canPlaySound)
    {
      result  = -1;
      running = 0;
    }

  if(running)
    {
      _set_dec00_cel_pos(eccb1);
      _set_dec00_cel_pos(eccb1w);
      _set_dec00_cel_pos(eccb2);
      _set_dec00_cel_pos(eccb2w);
      eccb1->ccb_XPos  = 0;
      eccb1->ccb_YPos  = 0;
      eccb2->ccb_XPos  = 0;
      eccb2->ccb_YPos  = 0;
      eccb1w->ccb_XPos = 0x500000;
      eccb1w->ccb_YPos = 0;
      eccb2w->ccb_XPos = 0x500000;
      eccb2w->ccb_YPos = 0;

      _set_dec00_render_flags(choice);
      sprintf((char *)scoreText, "SCORES:%d", point);

      while(running && ticks < DEC00_TIMEOUT)
        {
          WaitVBL(vblIOReq, 1);
          audioResult = DecisionAudioService(&decisionAudio);
          buttons     = GetJoypad();

          if(audioResult < 0)
            {
              canPlaySound = 0;
              result       = -1;
              running      = 0;
            }
          else if(controlPadLastError < 0)
            {
              result  = -1;
              running = 0;
            }
          else if(buttons == (int32)CONTROL_A)
            {
              result  = choice;
              running = 0;
            }
          else if(buttons == (int32)CONTROL_DOWN)
            {
              choice++;
              if(choice > 2)
                {
                  choice = 1;
                }
              _set_dec00_render_flags(choice);
              ticks            = 0;
            }
          else if(buttons == (int32)CONTROL_LEFT_SHIFT)
            {
              helpVisible = 1;
              ticks       = 0;
            }
          else if(buttons == (int32)CONTROL_UP)
            {
              choice--;
              if(choice < 1)
                {
                  choice = 2;
                }
              _set_dec00_render_flags(choice);
              ticks            = 0;
            }

          _draw_dec00_scene(vramIOReq, &gcon, scoreText, eccb1, eccb1w, eccb2, eccb2w, controlhelp,
                            helpVisible);
          if(helpVisible)
            {
              helpVisible = 0;
              continue;
            }

          if(running && audioEnabled && canPlaySound && choice != voicedChoice)
            {
              if(choice == 1)
                {
                  sound_name = (const uint8 *)DEC00_SOUND1;
                }
              else
                {
                  sound_name = (const uint8 *)DEC00_SOUND2;
                }

              audioResult =
                DecisionAudioStart(&decisionAudio, (uint8 *)sound_name, PDWT_SOUNDFILE_BUFFER_SIZE,
                                   PDWT_SOUNDFILE_AMPLITUDE);
              if(audioResult < 0)
                {
                  canPlaySound = 0;
                  result       = -1;
                  running      = 0;
                }
              else
                {
                  voicedChoice = choice;
                }
            }

          ticks++;
        }
    }

  _restore_next_screen(vramIOReq);

  audioResult = DecisionAudioStop(&decisionAudio);
  if(audioResult < 0 && result >= 0)
    {
      result = audioResult;
    }

  if(eventOpen)
    {
      KillEventUtility();
    }
  if(cel1Loaded)
    {
      UnloadCel(eccb1);
    }
  if(cel3Loaded)
    {
      UnloadCel(eccb2);
    }
  if(cel2Loaded)
    {
      UnloadCel(eccb1w);
    }
  if(cel4Loaded)
    {
      UnloadCel(eccb2w);
    }
  if(cel5Loaded)
    {
      UnloadCel(controlhelp);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }

  if(running && ticks >= DEC00_TIMEOUT && result >= 0)
    {
      result = 3;
    }
  return result;
}


int32
FunSC01(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC01_PATH_FORMAT, &FILE_SC01[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC01_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc01", _scene_table_fields(FILE_SC01, 39));

  while(frame < 1)
    {
      result = _draw_scene_table_frame(SC01_PATH_FORMAT, &FILE_SC01[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  while(frame < 39)
    {
      result = _draw_scene_table_frame(SC01_PATH_FORMAT, &FILE_SC01[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC01_PATH_FORMAT, &FILE_SC01[38], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC02(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC02_PATH_FORMAT, &FILE_SC02[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNSC02effectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC02_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(
    &sceneClock,
    (uint8 *)"sc02",
    _scene_table_fields(FILE_SC02, 24) - (uint32)FILE_SC02[4].CelLength + SC02_SHAKE_FIELDS);

  while(frame < 4)
    {
      result = _draw_scene_table_frame(SC02_PATH_FORMAT, &FILE_SC02[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  if(frame == 4)
    {
      cel = _load_scene_cel(SC02_PATH_FORMAT, &FILE_SC02[frame], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      _prepare_scene_cel(cel);
      result = shakeeffect(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
      result = _wait_for_scene_clock(&sceneClock, vblIOReq, SC02_SHAKE_FIELDS);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  while(frame < 24)
    {
      result = _draw_scene_table_frame(SC02_PATH_FORMAT, &FILE_SC02[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC02_PATH_FORMAT, &FILE_SC02[23], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC03(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC03_PATH_FORMAT, &FILE_SC03[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC03_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc03", _scene_table_fields(FILE_SC03, 10));

  while(frame < 10)
    {
      result = _draw_scene_table_frame(SC03_PATH_FORMAT, &FILE_SC03[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC03_PATH_FORMAT, &FILE_SC03[9], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC04(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  SceneCelInfo *table;
  char         *pathFormat;
  char         *soundFileName;
  Item vblIOReq;
  Item vramIOReq;
  CCB          *cel;
  CCB          *ratingCel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;
  int32 i;

  table         = secretpass ? FILE_SC44 : FILE_SC04;
  pathFormat    = secretpass ? SC04A_PATH_FORMAT : SC04_PATH_FORMAT;
  soundFileName = secretpass ? SC04A_SOUND_FILE : SC04_SOUND_FILE;
  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame         = 0;
  result        = 0;
  ratingCel     = 0;
  eventOpen     = 0;
  vblIOReq      = 0;
  vramIOReq     = 0;

  if(!secretpass)
    {
      ratingCel = LoadCel(SC04_RATING_CEL, PDWT_MEMTYPE_CEL);
      if(ratingCel == 0)
        {
          result = 1;
          goto cleanup;
        }
      ratingCel->ccb_XPos = 100 << 16;
      ratingCel->ccb_YPos = 90 << 16;
      ratingCel->ccb_Flags |= 0x40000000;
    }

  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(pathFormat, &table[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)soundFileName,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  if(ratingCel != 0)
    {
      PDWTSceneClockStart(
        &sceneClock,
        (uint8 *)"sc04",
        _scene_table_fields(table, SC04_RATING_START_FRAME) +
        ((23 - SC04_RATING_START_FRAME) * SC04_RATING_FIELDS));
    }
  else
    {
      PDWTSceneClockStart(&sceneClock, (uint8 *)"sc04", _scene_table_fields(table, 23));
    }

  while(frame < 5)
    {
      result = _draw_scene_table_frame(pathFormat, &table[frame], vramIOReq, vblIOReq, path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  while(frame < 23)
    {
      cel = _load_scene_cel(pathFormat, &table[frame], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      _prepare_scene_cel(cel);

      if(ratingCel != 0)
        {
          for(i = 0; i < SC04_RATING_FIELDS; i++)
            {
              result = _draw_scene_cel(vramIOReq, vblIOReq, cel, 1);
              if(result != 0)
                {
                  UnloadCel(cel);
                  goto cleanup;
                }
              if((i % 10) != 0)
                {
                  result = DrawCels(gScreenContext.sc_BitmapItems[gScreenContext.sc_curScreen],
                                    ratingCel);
                  if(result < 0)
                    {
                      UnloadCel(cel);
                      goto cleanup;
                    }
                }
            }
          result = _wait_for_scene_clock(&sceneClock, vblIOReq, SC04_RATING_FIELDS);
          if(result != 0)
            {
              UnloadCel(cel);
              goto cleanup;
            }
        }
      else
        {
          result = _draw_scene_cel(vramIOReq, vblIOReq, cel, 0);
          if(result == 0)
            {
              result = _wait_for_scene_clock(&sceneClock, vblIOReq, table[frame].CelLength);
            }
          if(result != 0)
            {
              UnloadCel(cel);
              goto cleanup;
            }
        }

      UnloadCel(cel);
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(pathFormat, &table[22], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectinh(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  if(ratingCel != 0)
    {
      UnloadCel(ratingCel);
    }
  _restore_next_screen(vramIOReq);
  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC06(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC06_PATH_FORMAT, &FILE_SC06[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectouth(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC06_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc06", _scene_table_fields(FILE_SC06, 53));

  while(frame < 53)
    {
      result = _draw_scene_table_frame(SC06_PATH_FORMAT, &FILE_SC06[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC06_PATH_FORMAT, &FILE_SC06[52], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC07(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC07_PATH_FORMAT, &FILE_SC07[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC07_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc07", _scene_table_fields(FILE_SC07, 15));

  while(frame < 15)
    {
      result = _draw_scene_table_frame(SC07_PATH_FORMAT, &FILE_SC07[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC07_PATH_FORMAT, &FILE_SC07[14], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
DEC07(void)
{
  return _run_standard_decision(&g_dec07_config);
}


int32
FunSC11(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC11_PATH_FORMAT, &FILE_SC11[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC11_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc11", _scene_table_fields(FILE_SC11, 13));

  while(frame < 13)
    {
      result = _draw_scene_table_frame(SC11_PATH_FORMAT, &FILE_SC11[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC11_PATH_FORMAT, &FILE_SC11[12], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC12(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC12_PATH_FORMAT, &FILE_SC12[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC12_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc12", _scene_table_fields(FILE_SC12, 43));

  while(frame < 43)
    {
      result = _draw_scene_table_frame(SC12_PATH_FORMAT, &FILE_SC12[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC12_PATH_FORMAT, &FILE_SC12[42], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
DEC12(void)
{
  return _run_standard_decision(&g_dec12_config);
}


int32
FunSC08(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC08_PATH_FORMAT, &FILE_SC08[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC08_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc08", _scene_table_fields(FILE_SC08, 11));

  while(frame < 11)
    {
      result = _draw_scene_table_frame(SC08_PATH_FORMAT, &FILE_SC08[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC08_PATH_FORMAT, &FILE_SC08[10], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
DEC08(void)
{
  return _run_standard_decision(&g_dec08_config);
}


int32
FunSC09(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC09_PATH_FORMAT, &FILE_SC09[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC09_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc09", _scene_table_fields(FILE_SC09, 17));

  while(frame < 17)
    {
      result = _draw_scene_table_frame(SC09_PATH_FORMAT, &FILE_SC09[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC09_PATH_FORMAT, &FILE_SC09[16], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC10(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC10_PATH_FORMAT, &FILE_SC10[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectout(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC10_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc10", _scene_table_fields(FILE_SC10, 6));

  while(frame < 6)
    {
      result = _draw_scene_table_frame(SC10_PATH_FORMAT, &FILE_SC10[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC10_PATH_FORMAT, &FILE_SC10[5], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
FunSC13(void)
{
  DecisionAudio sceneAudio;
  PDWTSceneControl sceneControl;
  PDWTSceneClock sceneClock;
  Item vblIOReq;
  Item vramIOReq;
  CCB  *cel;
  uint8 path[42];
  int32 eventOpen;
  int32 result;
  int32 frame;

  DecisionAudioInit(&sceneAudio);
  PDWTSceneControlInit(&sceneControl);
  memset(&sceneClock, 0, sizeof(sceneClock));
  frame     = 0;
  result    = 0;
  eventOpen = 0;
  vblIOReq  = GetVBLIOReq();
  vramIOReq = GetVRAMIOReq();
  if(vblIOReq < 0 || vramIOReq < 0)
    {
      result = 1;
      goto cleanup;
    }

  if(InitEventUtility(1, 0, 1) != 0)
    {
      eventOpen = 0;
      result    = 1;
      goto cleanup;
    }
  eventOpen = 1;
  result = PDWTSceneControlBegin(
    &sceneControl, &gScreenContext, vramIOReq, vblIOReq, &sceneAudio, &sceneClock);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  cel = _load_scene_cel(SC13_PATH_FORMAT, &FILE_SC13[0], path);
  if(cel == NULL)
    {
      result = 1;
      goto cleanup;
    }
  cel->ccb_Flags |= 0x40000000;
  result = FUNeffectouth(cel);
  UnloadCel(cel);
  if(result != PDWT_SCENE_CONTROL_CONTINUE)
    {
      goto cleanup;
    }

  result = DecisionAudioStartWithBuffers(
    &sceneAudio,
    (uint8 *)SC13_SOUND_FILE,
    PDWT_STORY_BUFFER_COUNT,
    PDWT_STORY_BUFFER_SIZE,
    PDWT_SOUNDFILE_AMPLITUDE);
  if(result < 0)
    {
      goto cleanup;
    }
  PDWTSceneClockStart(&sceneClock, (uint8 *)"sc13", _scene_table_fields(FILE_SC13, 11));

  while(frame < 11)
    {
      result = _draw_scene_table_frame(SC13_PATH_FORMAT, &FILE_SC13[frame], vramIOReq, vblIOReq,
                                       path,
                                       &sceneClock);
      if(result != 0)
        {
          goto cleanup;
        }
      frame++;
    }

  result = _wait_for_uncalibrated_scene_audio(&sceneClock, &sceneAudio, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

  if(result == 0)
    {
      cel = _load_scene_cel(SC13_PATH_FORMAT, &FILE_SC13[10], path);
      if(cel == NULL)
        {
          result = 1;
          goto cleanup;
        }
      cel->ccb_Flags |= 0x40000000;
      result = FUNeffectin(cel);
      UnloadCel(cel);
      if(result != 0)
        {
          goto cleanup;
        }
    }

  result = _wait_for_calibrated_scene_end(&sceneClock, vblIOReq);
  if(result != 0)
    {
      goto cleanup;
    }

cleanup:
  PDWTSceneControlEnd(&sceneControl);
  result = _stop_scene_audio(&sceneAudio, result);
  _restore_next_screen(vramIOReq);

  if(vblIOReq > 0)
    {
      DeleteItem(vblIOReq);
    }
  if(vramIOReq > 0)
    {
      DeleteItem(vramIOReq);
    }
  if(eventOpen)
    {
      int32 cleanup_result;

      cleanup_result = KillEventUtility();
      if((cleanup_result < 0) && (result >= 0))
        {
          result = cleanup_result;
        }
    }

  return _finish_scene_result(result);
}


int32
playplumber(void)
{
  int32 dec00Result;
  int32 dec07Result;
  int32 sceneResult;
  int32 preDec07Result;
  int32 dec13Result;

  point          = 0;
  startover      = 0;
  preDec07Result = 0;
  sceneResult    = 0;

start_dec00:
  dec00Result = DEC00();
  if(dec00Result < 0)
    {
      return dec00Result;
    }
  if(dec00Result == 0)
    {
      goto start_sc01;
    }
  if(dec00Result == 3)
    {
      return dec00Result;
    }
  if(dec00Result == 1)
    {
      point += 0x2710;
      sceneResult    = FunSC01();
      preDec07Result = sceneResult;
      if(sceneResult < 0)
        {
          return sceneResult;
        }
      if(sceneResult == 3)
        {
          point -= 0x2710;
          goto start_dec00;
        }
      goto start_sc02;
    }
  goto start_dec07;

start_sc01:
  sceneResult    = FunSC01();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_dec00;
    }

start_sc02:
  sceneResult    = FunSC02();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc01;
    }

start_sc03:
  sceneResult    = FunSC03();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc02;
    }

start_sc04:
  sceneResult    = FunSC04();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc03;
    }

start_sc06:
  sceneResult    = FunSC06();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc04;
    }

start_sc07:
  sceneResult    = FunSC07();
  preDec07Result = sceneResult;
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc06;
    }

start_dec07:
  dec07Result = DEC07();
  if(dec07Result < 0)
    {
      return dec07Result;
    }
  if(dec07Result == 0)
    {
      goto start_sc08_with_backtrack;
    }
  if(dec07Result == 5)
    {
      if(preDec07Result != 0)
        {
          goto start_sc07;
        }
      goto start_dec00;
    }
  if(dec07Result == 1)
    {
      point += 0x2710;
      goto start_sc08_with_backtrack;
    }
  if(dec07Result == 2)
    {
      goto start_sc11_path;
    }
  if(dec07Result == 3)
    {
      goto start_sc12_path;
    }
  return 0;

start_sc08_with_backtrack:
  sceneResult = FunSC08();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      point -= 0x2710;
      goto start_dec07;
    }

start_dec08:
  sceneResult = DEC08();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 0)
    {
      goto start_sc09;
    }
  if(sceneResult == 1)
    {
      point += 0x2710;
      goto start_sc09;
    }
  if(sceneResult == 2)
    {
      goto start_sc10_path;
    }
  if(sceneResult == 3)
    {
      goto start_sc08_with_backtrack;
    }
  goto after_dec07_paths;

start_sc09:
  sceneResult = FunSC09();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      point -= 0x2710;
      goto start_dec08;
    }

start_sc13_after_sc09:
  sceneResult = FunSC13();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto start_sc09;
    }
  dec13Result = DEC13();
  if(dec13Result < 0)
    {
      return dec13Result;
    }
  if(dec13Result == 25)
    {
      goto start_sc13_after_sc09;
    }
  if(dec13Result == 50)
    {
      goto start_dec07;
    }
  if(dec13Result == 100)
    {
      return dec13Result;
    }
  goto start_dec07;

start_sc10_path:
  point += 0x2710;

replay_sc10:
  sceneResult = FunSC10();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      point -= 0x2710;
      goto start_dec08;
    }

start_sc13_after_sc10:
  sceneResult = FunSC13();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto replay_sc10;
    }
  dec13Result = DEC13();
  if(dec13Result < 0)
    {
      return dec13Result;
    }
  if(dec13Result == 25)
    {
      goto start_sc13_after_sc10;
    }
  if(dec13Result == 50)
    {
      goto start_dec07;
    }
  if(dec13Result == 100)
    {
      return dec13Result;
    }
  goto start_dec07;

start_sc11_path:
  point += 0x2710;

replay_sc11:
  sceneResult = FunSC11();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      point -= 0x2710;
      goto start_dec07;
    }

start_sc13_after_sc11:
  sceneResult = FunSC13();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      goto replay_sc11;
    }
  dec13Result = DEC13();
  if(dec13Result < 0)
    {
      return dec13Result;
    }
  if(dec13Result == 25)
    {
      goto start_sc13_after_sc11;
    }
  if(dec13Result == 50)
    {
      goto start_dec07;
    }
  if(dec13Result == 100)
    {
      return dec13Result;
    }
  goto start_dec07;

start_sc12_path:
  point -= 0x4e20;

start_sc12_scene:
  sceneResult = FunSC12();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 3)
    {
      point += 0x4e20;
      goto start_dec07;
    }

  sceneResult = DEC12();
  if(sceneResult < 0)
    {
      return sceneResult;
    }
  if(sceneResult == 0)
    {
      goto start_sc12_scene;
    }
  if(sceneResult == 1)
    {
      goto start_dec07;
    }
  if(sceneResult == 3)
    {
      goto start_sc12_scene;
    }
  if(sceneResult != 0)
    {
      return sceneResult;
    }

after_dec07_paths:
  return 0;
}
