/* ============================================================================
 * Reconstructed source: :Streammike.c
 * Generated by armfd --reconstruct-sources from launchme.sym
 * ============================================================================ */

// Streammike.c - data-streaming wrapper.
//
// Reconstructed from the two small wrapper functions in :Objects:Streammike.c.o.
#include "pdwt_stream.h"

#include "3do_types.h"
#include "pdwt_app.h"

#include "datastreamdebug.h"

int32
playdatastream(uint8         *streamname_,
               PlayCPakUserFn myUserFunction_)
{
  int32 err;

  err = PlayCPakStream(&gScreenContext, streamname_, myUserFunction_);
  if(err < 0)
    {
      PrintfDSError(err);
      return err;
    }

  return err;
}


int32
playdatastreams(uint8         *streamname_,
                PlayCPakUserFn mySecretFun_)
{
  int32 err;

  err = PlayCPakStream(&gScreenContext, streamname_, mySecretFun_);
  if(err < 0)
    {
      PrintfDSError(err);
      return err;
    }

  return err;
}
